DROP DATABASE albalbcardb;

CREATE SCHEMA IF NOT EXISTS albalbcardb;

USE albalbcardb; 

CREATE TABLE IF NOT EXISTS roles(
	RoleID INT NOT NULL PRIMARY KEY,
    userRole VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
	login VARCHAR(100) NOT NULL PRIMARY KEY,
    password1 VARCHAR(100) NOT NULL,
	phoneNumber VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS users_roles(
	RoleID INT NOT NULL,
    login VARCHAR(100) NOT NULL,
	FOREIGN KEY (RoleID) REFERENCES roles(RoleID),
    FOREIGN KEY (login) REFERENCES users(login)
);

CREATE TABLE IF NOT EXISTS cities(
    cityName VARCHAR(100) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS rides(
	rideID INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS rides_cities(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cityName VARCHAR(100) NOT NULL,
    rideID INT NOT NULL,
    price DECIMAL(6,2) NOT NULL,
    stopNumer INT NOT NULL,
    leavingTime TIME,
    numberOfPlaces INT NOT NULL,
    FOREIGN KEY (cityName) REFERENCES cities(cityName),
    FOREIGN KEY (rideID) REFERENCES rides(rideID)
);
    
INSERT INTO roles VALUES (1,'admin');
INSERT INTO roles VALUES (2,'user');
INSERT INTO users VALUES ('jop','pass','231213123');
INSERT INTO users_roles VALUES (1,'jop');

INSERT INTO cities VALUES ('Warszawa');
INSERT INTO cities VALUES ('Aleksandrów Kujawski');
INSERT INTO cities VALUES ('Aleksandrów Łódzki');
INSERT INTO cities VALUES ('Alwernia');
INSERT INTO cities VALUES ('Andrychów');
INSERT INTO cities VALUES ('Annopol');
INSERT INTO cities VALUES ('Augustów');
INSERT INTO cities VALUES ('Babimost');
INSERT INTO cities VALUES ('Baborów');
INSERT INTO cities VALUES ('Baranów Sandomierski');
INSERT INTO cities VALUES ('Barcin');
INSERT INTO cities VALUES ('Barczewo');
INSERT INTO cities VALUES ('Bardo');
INSERT INTO cities VALUES ('Barlinek');
INSERT INTO cities VALUES ('Bartoszyce');
INSERT INTO cities VALUES ('Barwice');
INSERT INTO cities VALUES ('Bełchatów');
INSERT INTO cities VALUES ('Bełżyce');
INSERT INTO cities VALUES ('Będzin');
INSERT INTO cities VALUES ('Biała');
INSERT INTO cities VALUES ('Biała Piska');
INSERT INTO cities VALUES ('Biała Podlaska');
INSERT INTO cities VALUES ('Biała Rawska');
INSERT INTO cities VALUES ('Białobrzegi');
INSERT INTO cities VALUES ('Białogard');
INSERT INTO cities VALUES ('Biały Bór');
INSERT INTO cities VALUES ('Białystok');
INSERT INTO cities VALUES ('Biecz');
INSERT INTO cities VALUES ('Bielawa');
INSERT INTO cities VALUES ('Bielsk Podlaski');
INSERT INTO cities VALUES ('Bielsko-Biała');
INSERT INTO cities VALUES ('Bieruń');
INSERT INTO cities VALUES ('Bierutów');
INSERT INTO cities VALUES ('Bieżuń');
INSERT INTO cities VALUES ('Biłgoraj');
INSERT INTO cities VALUES ('Biskupiec');
INSERT INTO cities VALUES ('Bisztynek');
INSERT INTO cities VALUES ('Blachownia');
INSERT INTO cities VALUES ('Błaszki');
INSERT INTO cities VALUES ('Błażowa');
INSERT INTO cities VALUES ('Błonie');
INSERT INTO cities VALUES ('Bobolice');
INSERT INTO cities VALUES ('Bobowa');
INSERT INTO cities VALUES ('Bochnia');
INSERT INTO cities VALUES ('Bodzentyn');
INSERT INTO cities VALUES ('Bogatynia');
INSERT INTO cities VALUES ('Boguchwała');
INSERT INTO cities VALUES ('Boguszów-Gorce');
INSERT INTO cities VALUES ('Bojanowo');
INSERT INTO cities VALUES ('Bolesławiec');
INSERT INTO cities VALUES ('Bolków');
INSERT INTO cities VALUES ('Borek Wielkopolski');
INSERT INTO cities VALUES ('Borne Sulinowo');
INSERT INTO cities VALUES ('Braniewo');
INSERT INTO cities VALUES ('Brańsk');
INSERT INTO cities VALUES ('Brodnica');
INSERT INTO cities VALUES ('Brok');
INSERT INTO cities VALUES ('Brusy');
INSERT INTO cities VALUES ('Brwinów');
INSERT INTO cities VALUES ('Brzeg');
INSERT INTO cities VALUES ('Brzeg Dolny');
INSERT INTO cities VALUES ('Brzesko');
INSERT INTO cities VALUES ('Brzeszcze');
INSERT INTO cities VALUES ('Brześć Kujawski');
INSERT INTO cities VALUES ('Brzeziny');
INSERT INTO cities VALUES ('Brzostek');
INSERT INTO cities VALUES ('Brzozów');
INSERT INTO cities VALUES ('Buk');
INSERT INTO cities VALUES ('Bukowno');
INSERT INTO cities VALUES ('Busko-Zdrój');
INSERT INTO cities VALUES ('Bychawa');
INSERT INTO cities VALUES ('Byczyna');
INSERT INTO cities VALUES ('Bydgoszcz');
INSERT INTO cities VALUES ('Bystrzyca Kłodzka');
INSERT INTO cities VALUES ('Bytom');
INSERT INTO cities VALUES ('Bytom Odrzański');
INSERT INTO cities VALUES ('Bytów');
INSERT INTO cities VALUES ('Cedynia');
INSERT INTO cities VALUES ('Chełm');
INSERT INTO cities VALUES ('Chełmek');
INSERT INTO cities VALUES ('Chełmno');
INSERT INTO cities VALUES ('Chełmża');
INSERT INTO cities VALUES ('Chęciny');
INSERT INTO cities VALUES ('Chmielnik');
INSERT INTO cities VALUES ('Chocianów');
INSERT INTO cities VALUES ('Chociwel');
INSERT INTO cities VALUES ('Chocz');
INSERT INTO cities VALUES ('Chodecz');
INSERT INTO cities VALUES ('Chodzież');
INSERT INTO cities VALUES ('Chojna');
INSERT INTO cities VALUES ('Chojnice');
INSERT INTO cities VALUES ('Chojnów');
INSERT INTO cities VALUES ('Choroszcz');
INSERT INTO cities VALUES ('Chorzele');
INSERT INTO cities VALUES ('Chorzów');
INSERT INTO cities VALUES ('Choszczno');
INSERT INTO cities VALUES ('Chrzanów');
INSERT INTO cities VALUES ('Ciechanowiec');
INSERT INTO cities VALUES ('Ciechanów');
INSERT INTO cities VALUES ('Ciechocinek');
INSERT INTO cities VALUES ('Cieszanów');
INSERT INTO cities VALUES ('Cieszyn');
INSERT INTO cities VALUES ('Ciężkowice');
INSERT INTO cities VALUES ('Cybinka');
INSERT INTO cities VALUES ('Czaplinek');
INSERT INTO cities VALUES ('Czarna Białostocka');
INSERT INTO cities VALUES ('Czarna Woda');
INSERT INTO cities VALUES ('Czarne');
INSERT INTO cities VALUES ('Czarnków');
INSERT INTO cities VALUES ('Czchów');
INSERT INTO cities VALUES ('Czechowice-Dziedzice');
INSERT INTO cities VALUES ('Czeladź');
INSERT INTO cities VALUES ('Czempiń');
INSERT INTO cities VALUES ('Czerniejewo');
INSERT INTO cities VALUES ('Czersk');
INSERT INTO cities VALUES ('Czerwieńsk');
INSERT INTO cities VALUES ('Czerwionka-Leszczyny');
INSERT INTO cities VALUES ('Częstochowa');
INSERT INTO cities VALUES ('Człopa');
INSERT INTO cities VALUES ('Człuchów');
INSERT INTO cities VALUES ('Czyżew');
INSERT INTO cities VALUES ('Ćmielów');
INSERT INTO cities VALUES ('Daleszyce');
INSERT INTO cities VALUES ('Darłowo');
INSERT INTO cities VALUES ('Dąbie');
INSERT INTO cities VALUES ('Dąbrowa Białostocka');
INSERT INTO cities VALUES ('Dąbrowa Górnicza');
INSERT INTO cities VALUES ('Dąbrowa Tarnowska');
INSERT INTO cities VALUES ('Debrzno');
INSERT INTO cities VALUES ('Dębica');
INSERT INTO cities VALUES ('Dęblin');
INSERT INTO cities VALUES ('Dębno');
INSERT INTO cities VALUES ('Dobczyce');
INSERT INTO cities VALUES ('Dobiegniew');
INSERT INTO cities VALUES ('Dobra');

INSERT INTO cities VALUES ('Dobre Miasto');
INSERT INTO cities VALUES ('Dobrodzień');
INSERT INTO cities VALUES ('Dobrzany');
INSERT INTO cities VALUES ('Dobrzyca');
INSERT INTO cities VALUES ('Dobrzyń nad');
INSERT INTO cities VALUES ('Wisłą');
INSERT INTO cities VALUES ('Dolsk');
INSERT INTO cities VALUES ('Drawno');
INSERT INTO cities VALUES ('Drawsko Pomorskie');
INSERT INTO cities VALUES ('Drezdenko');
INSERT INTO cities VALUES ('Drobin');
INSERT INTO cities VALUES ('Drohiczyn');
INSERT INTO cities VALUES ('Drzewica');
INSERT INTO cities VALUES ('Dukla');
INSERT INTO cities VALUES ('Duszniki-Zdrój');
INSERT INTO cities VALUES ('Dynów');
INSERT INTO cities VALUES ('Działdowo');
INSERT INTO cities VALUES ('Działoszyce');
INSERT INTO cities VALUES ('Działoszyn');
INSERT INTO cities VALUES ('Dzierzgoń');
INSERT INTO cities VALUES ('Dzierżoniów');
INSERT INTO cities VALUES ('Dziwnów');
INSERT INTO cities VALUES ('Elbląg');
INSERT INTO cities VALUES ('Ełk');
INSERT INTO cities VALUES ('Frampol');
INSERT INTO cities VALUES ('Frombork');
INSERT INTO cities VALUES ('Garwolin');
INSERT INTO cities VALUES ('Gąbin');
INSERT INTO cities VALUES ('Gdańsk');
INSERT INTO cities VALUES ('Gdynia');
INSERT INTO cities VALUES ('Giżycko');
INSERT INTO cities VALUES ('Glinojeck');
INSERT INTO cities VALUES ('Gliwice');
INSERT INTO cities VALUES ('Głogów');
INSERT INTO cities VALUES ('Głogów Małopolski');
INSERT INTO cities VALUES ('Głogówek');
INSERT INTO cities VALUES ('Głowno');
INSERT INTO cities VALUES ('Głubczyce');
INSERT INTO cities VALUES ('Głuchołazy');
INSERT INTO cities VALUES ('Głuszyca');
INSERT INTO cities VALUES ('Gniew');
INSERT INTO cities VALUES ('Gniewkowo');
INSERT INTO cities VALUES ('Gniezno');
INSERT INTO cities VALUES ('Gogolin');
INSERT INTO cities VALUES ('Golczewo');
INSERT INTO cities VALUES ('Goleniów');
INSERT INTO cities VALUES ('Golina');
INSERT INTO cities VALUES ('Golub-Dobrzyń');
INSERT INTO cities VALUES ('Gołańcz');
INSERT INTO cities VALUES ('Gołdap');
INSERT INTO cities VALUES ('Goniądz');
INSERT INTO cities VALUES ('Gorlice');
INSERT INTO cities VALUES ('Gorzów Śląski');
INSERT INTO cities VALUES ('Gorzów Wielkopolski');
INSERT INTO cities VALUES ('Gostynin');
INSERT INTO cities VALUES ('Gostyń');
INSERT INTO cities VALUES ('Gościno');
INSERT INTO cities VALUES ('Gozdnica');
INSERT INTO cities VALUES ('Góra');
INSERT INTO cities VALUES ('Góra Kalwaria');
INSERT INTO cities VALUES ('Górowo Iławeckie');
INSERT INTO cities VALUES ('Górzno');
INSERT INTO cities VALUES ('Grabów nad');
INSERT INTO cities VALUES ('Prosną');
INSERT INTO cities VALUES ('Grajewo');
INSERT INTO cities VALUES ('Grodków');
INSERT INTO cities VALUES ('Grodzisk Mazowiecki');
INSERT INTO cities VALUES ('Grodzisk Wielkopolski');
INSERT INTO cities VALUES ('Grójec');
INSERT INTO cities VALUES ('Grudziądz');
INSERT INTO cities VALUES ('Grybów');
INSERT INTO cities VALUES ('Gryfice');
INSERT INTO cities VALUES ('Gryfino');
INSERT INTO cities VALUES ('Gryfów Śląski');
INSERT INTO cities VALUES ('Gubin');
INSERT INTO cities VALUES ('Hajnówka');
INSERT INTO cities VALUES ('Halinów');
INSERT INTO cities VALUES ('Hel');
INSERT INTO cities VALUES ('Hrubieszów');
INSERT INTO cities VALUES ('Iława');
INSERT INTO cities VALUES ('Iłowa');
INSERT INTO cities VALUES ('Iłża');
INSERT INTO cities VALUES ('Imielin');
INSERT INTO cities VALUES ('Inowrocław');
INSERT INTO cities VALUES ('Ińsko');
INSERT INTO cities VALUES ('Iwonicz-Zdrój');
INSERT INTO cities VALUES ('Izbica Kujawska');
INSERT INTO cities VALUES ('Jabłonowo Pomorskie');
INSERT INTO cities VALUES ('Janikowo');
INSERT INTO cities VALUES ('Janowiec Wielkopolski');
INSERT INTO cities VALUES ('Janów Lubelski');
INSERT INTO cities VALUES ('Jaraczewo');
INSERT INTO cities VALUES ('Jarocin');
INSERT INTO cities VALUES ('Jarosław');
INSERT INTO cities VALUES ('Jasień');
INSERT INTO cities VALUES ('Jasło');
INSERT INTO cities VALUES ('Jastarnia');
INSERT INTO cities VALUES ('Jastrowie');
INSERT INTO cities VALUES ('Jastrzębie-Zdrój');
INSERT INTO cities VALUES ('Jawor');
INSERT INTO cities VALUES ('Jaworzno');
INSERT INTO cities VALUES ('Jaworzyna Śląska');
INSERT INTO cities VALUES ('Jedlicze');
INSERT INTO cities VALUES ('Jedlina-Zdrój');
INSERT INTO cities VALUES ('Jedwabne');
INSERT INTO cities VALUES ('Jelcz-Laskowice');
INSERT INTO cities VALUES ('Jelenia Góra');
INSERT INTO cities VALUES ('Jeziorany');
INSERT INTO cities VALUES ('Jędrzejów');
INSERT INTO cities VALUES ('Jordanów');
INSERT INTO cities VALUES ('Józefów');

INSERT INTO cities VALUES ('Jutrosin');
INSERT INTO cities VALUES ('Kalety');
INSERT INTO cities VALUES ('Kalisz');
INSERT INTO cities VALUES ('Kalisz Pomorski');
INSERT INTO cities VALUES ('Kalwaria Zebrzydowska');
INSERT INTO cities VALUES ('Kałuszyn');
INSERT INTO cities VALUES ('Kamienna Góra');
INSERT INTO cities VALUES ('Kamień Krajeński');
INSERT INTO cities VALUES ('Kamień Pomorski');
INSERT INTO cities VALUES ('Kamieńsk');
INSERT INTO cities VALUES ('Kańczuga');
INSERT INTO cities VALUES ('Karczew');
INSERT INTO cities VALUES ('Kargowa');
INSERT INTO cities VALUES ('Karlino');
INSERT INTO cities VALUES ('Karpacz');
INSERT INTO cities VALUES ('Kartuzy');
INSERT INTO cities VALUES ('Katowice');
INSERT INTO cities VALUES ('Kazimierz Dolny');
INSERT INTO cities VALUES ('Kazimierza Wielka');
INSERT INTO cities VALUES ('Kąty Wrocławskie');
INSERT INTO cities VALUES ('Kcynia');
INSERT INTO cities VALUES ('Kędzierzyn-Koźle');
INSERT INTO cities VALUES ('Kępice');
INSERT INTO cities VALUES ('Kępno');
INSERT INTO cities VALUES ('Kętrzyn');
INSERT INTO cities VALUES ('Kęty');
INSERT INTO cities VALUES ('Kielce');
INSERT INTO cities VALUES ('Kietrz');
INSERT INTO cities VALUES ('Kisielice');
INSERT INTO cities VALUES ('Kleczew');
INSERT INTO cities VALUES ('Kleszczele');
INSERT INTO cities VALUES ('Kluczbork');
INSERT INTO cities VALUES ('Kłecko');
INSERT INTO cities VALUES ('Kłobuck');
INSERT INTO cities VALUES ('Kłodawa');
INSERT INTO cities VALUES ('Kłodzko');
INSERT INTO cities VALUES ('Knurów');
INSERT INTO cities VALUES ('Knyszyn');
INSERT INTO cities VALUES ('Kobylin');
INSERT INTO cities VALUES ('Kobyłka');
INSERT INTO cities VALUES ('Kock');
INSERT INTO cities VALUES ('Kolbuszowa');
INSERT INTO cities VALUES ('Kolno');
INSERT INTO cities VALUES ('Kolonowskie');
INSERT INTO cities VALUES ('Koluszki');
INSERT INTO cities VALUES ('Kołaczyce');
INSERT INTO cities VALUES ('Koło');
INSERT INTO cities VALUES ('Kołobrzeg');
INSERT INTO cities VALUES ('Koniecpol');
INSERT INTO cities VALUES ('Konin');
INSERT INTO cities VALUES ('Konstancin-Jeziorna');
INSERT INTO cities VALUES ('Konstantynów Łódzki');
INSERT INTO cities VALUES ('Końskie');
INSERT INTO cities VALUES ('Koprzywnica');
INSERT INTO cities VALUES ('Korfantów');
INSERT INTO cities VALUES ('Koronowo');
INSERT INTO cities VALUES ('Korsze');
INSERT INTO cities VALUES ('Kosów Lacki');
INSERT INTO cities VALUES ('Kostrzyn');
INSERT INTO cities VALUES ('Kostrzyn nad');
INSERT INTO cities VALUES ('Odrą');
INSERT INTO cities VALUES ('Koszalin');
INSERT INTO cities VALUES ('Kościan');
INSERT INTO cities VALUES ('Kościerzyna');
INSERT INTO cities VALUES ('Kowal');
INSERT INTO cities VALUES ('Kowalewo Pomorskie');
INSERT INTO cities VALUES ('Kowary');
INSERT INTO cities VALUES ('Koziegłowy');
INSERT INTO cities VALUES ('Kozienice');
INSERT INTO cities VALUES ('Koźmin Wielkopolski');
INSERT INTO cities VALUES ('Kożuchów');
INSERT INTO cities VALUES ('Kórnik');
INSERT INTO cities VALUES ('Krajenka');
INSERT INTO cities VALUES ('Kraków');
INSERT INTO cities VALUES ('Krapkowice');
INSERT INTO cities VALUES ('Krasnobród');
INSERT INTO cities VALUES ('Krasnystaw');
INSERT INTO cities VALUES ('Kraśnik');
INSERT INTO cities VALUES ('Krobia');
INSERT INTO cities VALUES ('Krosno');
INSERT INTO cities VALUES ('Krosno Odrzańskie');
INSERT INTO cities VALUES ('Krośniewice');
INSERT INTO cities VALUES ('Krotoszyn');
INSERT INTO cities VALUES ('Kruszwica');
INSERT INTO cities VALUES ('Krynica Morska');
INSERT INTO cities VALUES ('Krynica-Zdrój');
INSERT INTO cities VALUES ('Krynki');
INSERT INTO cities VALUES ('Krzanowice');
INSERT INTO cities VALUES ('Krzepice');
INSERT INTO cities VALUES ('Krzeszowice');
INSERT INTO cities VALUES ('Krzywiń');
INSERT INTO cities VALUES ('Krzyż Wielkopolski');
INSERT INTO cities VALUES ('Książ Wielkopolski');
INSERT INTO cities VALUES ('Kudowa-Zdrój');
INSERT INTO cities VALUES ('Kunów');
INSERT INTO cities VALUES ('Kutno');
INSERT INTO cities VALUES ('Kuźnia Raciborska');
INSERT INTO cities VALUES ('Kwidzyn');
INSERT INTO cities VALUES ('Lądek-Zdrój');
INSERT INTO cities VALUES ('Legionowo');
INSERT INTO cities VALUES ('Legnica');
INSERT INTO cities VALUES ('Lesko');
INSERT INTO cities VALUES ('Leszno');
INSERT INTO cities VALUES ('Leśna');
INSERT INTO cities VALUES ('Leśnica');
INSERT INTO cities VALUES ('Lewin Brzeski');
INSERT INTO cities VALUES ('Leżajsk');
INSERT INTO cities VALUES ('Lębork');
INSERT INTO cities VALUES ('Lędziny');
INSERT INTO cities VALUES ('Libiąż');
INSERT INTO cities VALUES ('Lidzbark');
INSERT INTO cities VALUES ('Lidzbark Warmiński');
INSERT INTO cities VALUES ('Limanowa');
INSERT INTO cities VALUES ('Lipiany');
INSERT INTO cities VALUES ('Lipno');
INSERT INTO cities VALUES ('Lipsk');
INSERT INTO cities VALUES ('Lipsko');
INSERT INTO cities VALUES ('Lubaczów');
INSERT INTO cities VALUES ('Lubań');
INSERT INTO cities VALUES ('Lubartów');
INSERT INTO cities VALUES ('Lubawa');
INSERT INTO cities VALUES ('Lubawka');
INSERT INTO cities VALUES ('Lubień Kujawski');
INSERT INTO cities VALUES ('Lubin');
INSERT INTO cities VALUES ('Lublin');
INSERT INTO cities VALUES ('Lubliniec');
INSERT INTO cities VALUES ('Lubniewice');
INSERT INTO cities VALUES ('Lubomierz');
INSERT INTO cities VALUES ('Luboń');
INSERT INTO cities VALUES ('Lubraniec');
INSERT INTO cities VALUES ('Lubsko');
INSERT INTO cities VALUES ('Lubycza Królewska');
INSERT INTO cities VALUES ('Lwówek');
INSERT INTO cities VALUES ('Lwówek Śląski');
INSERT INTO cities VALUES ('Łabiszyn');
INSERT INTO cities VALUES ('Łańcut');
INSERT INTO cities VALUES ('Łapy');
INSERT INTO cities VALUES ('Łasin');
INSERT INTO cities VALUES ('Łask');
INSERT INTO cities VALUES ('Łaskarzew');
INSERT INTO cities VALUES ('Łaszczów');
INSERT INTO cities VALUES ('Łaziska Górne');
INSERT INTO cities VALUES ('Łazy');
INSERT INTO cities VALUES ('Łeba');
INSERT INTO cities VALUES ('Łęczna');
INSERT INTO cities VALUES ('Łęczyca');
INSERT INTO cities VALUES ('Łęknica');
INSERT INTO cities VALUES ('Łobez');
INSERT INTO cities VALUES ('Łobżenica');
INSERT INTO cities VALUES ('Łochów');
INSERT INTO cities VALUES ('Łomianki');
INSERT INTO cities VALUES ('Łomża');
INSERT INTO cities VALUES ('Łosice');
INSERT INTO cities VALUES ('Łowicz');
INSERT INTO cities VALUES ('Łódź');
INSERT INTO cities VALUES ('Łuków');
INSERT INTO cities VALUES ('Maków Mazowiecki');
INSERT INTO cities VALUES ('Maków Podhalański');
INSERT INTO cities VALUES ('Malbork');
INSERT INTO cities VALUES ('Małogoszcz');
INSERT INTO cities VALUES ('Małomice');
INSERT INTO cities VALUES ('Margonin');
INSERT INTO cities VALUES ('Marki');
INSERT INTO cities VALUES ('Maszewo');
INSERT INTO cities VALUES ('Miasteczko Śląskie');
INSERT INTO cities VALUES ('Miastko');
INSERT INTO cities VALUES ('Michałowo');
INSERT INTO cities VALUES ('Miechów');
INSERT INTO cities VALUES ('Miejska Górka');
INSERT INTO cities VALUES ('Mielec');
INSERT INTO cities VALUES ('Mieroszów');
INSERT INTO cities VALUES ('Mieszkowice');
INSERT INTO cities VALUES ('Międzybórz');
INSERT INTO cities VALUES ('Międzychód');
INSERT INTO cities VALUES ('Międzylesie');
INSERT INTO cities VALUES ('Międzyrzec Podlaski');
INSERT INTO cities VALUES ('Międzyrzecz');
INSERT INTO cities VALUES ('Międzyzdroje');
INSERT INTO cities VALUES ('Mikołajki');
INSERT INTO cities VALUES ('Mikołów');
INSERT INTO cities VALUES ('Mikstat');
INSERT INTO cities VALUES ('Milanówek');
INSERT INTO cities VALUES ('Milicz');
INSERT INTO cities VALUES ('Miłakowo');
INSERT INTO cities VALUES ('Miłomłyn');
INSERT INTO cities VALUES ('Miłosław');
INSERT INTO cities VALUES ('Mińsk Mazowiecki');
INSERT INTO cities VALUES ('Mirosławiec');
INSERT INTO cities VALUES ('Mirsk');
INSERT INTO cities VALUES ('Mława');
INSERT INTO cities VALUES ('Młynary');
INSERT INTO cities VALUES ('Modliborzyce');
INSERT INTO cities VALUES ('Mogielnica');
INSERT INTO cities VALUES ('Mogilno');
INSERT INTO cities VALUES ('Mońki');
INSERT INTO cities VALUES ('Morąg');
INSERT INTO cities VALUES ('Mordy');
INSERT INTO cities VALUES ('Moryń');
INSERT INTO cities VALUES ('Mosina');
INSERT INTO cities VALUES ('Mrągowo');
INSERT INTO cities VALUES ('Mrocza');
INSERT INTO cities VALUES ('Mrozy');
INSERT INTO cities VALUES ('Mszana Dolna');
INSERT INTO cities VALUES ('Mszczonów');
INSERT INTO cities VALUES ('Murowana Goślina');
INSERT INTO cities VALUES ('Muszyna');
INSERT INTO cities VALUES ('Mysłowice');
INSERT INTO cities VALUES ('Myszków');
INSERT INTO cities VALUES ('Myszyniec');
INSERT INTO cities VALUES ('Myślenice');
INSERT INTO cities VALUES ('Myślibórz');
INSERT INTO cities VALUES ('Nakło nad');
INSERT INTO cities VALUES ('Notecią');
INSERT INTO cities VALUES ('Nałęczów');
INSERT INTO cities VALUES ('Namysłów');
INSERT INTO cities VALUES ('Narol');
INSERT INTO cities VALUES ('Nasielsk');
INSERT INTO cities VALUES ('Nekla');
INSERT INTO cities VALUES ('Nidzica');
INSERT INTO cities VALUES ('Niemcza');
INSERT INTO cities VALUES ('Niemodlin');
INSERT INTO cities VALUES ('Niepołomice');
INSERT INTO cities VALUES ('Nieszawa');
INSERT INTO cities VALUES ('Nisko');
INSERT INTO cities VALUES ('Nowa Dęba');
INSERT INTO cities VALUES ('Nowa Ruda');
INSERT INTO cities VALUES ('Nowa Sarzyna');
INSERT INTO cities VALUES ('Nowa Sól');
INSERT INTO cities VALUES ('Nowe');
INSERT INTO cities VALUES ('Nowe Brzesko');
INSERT INTO cities VALUES ('Nowe Miasteczko');
INSERT INTO cities VALUES ('Nowe Miasto');
INSERT INTO cities VALUES ('Lubawskie');
INSERT INTO cities VALUES ('Nowe Miasto nad Pilicą');

INSERT INTO cities VALUES ('Nowe Skalmierzyce');
INSERT INTO cities VALUES ('Nowe Warpno');
INSERT INTO cities VALUES ('Nowogard');
INSERT INTO cities VALUES ('Nowogrodziec');
INSERT INTO cities VALUES ('Nowogród');
INSERT INTO cities VALUES ('Nowogród Bobrzański');
INSERT INTO cities VALUES ('Nowy Dwór Gdański');

INSERT INTO cities VALUES ('Nowy Dwór');
INSERT INTO cities VALUES ('Mazowiecki');
INSERT INTO cities VALUES ('Nowy Sącz');
INSERT INTO cities VALUES ('Nowy Staw');
INSERT INTO cities VALUES ('Nowy Targ');
INSERT INTO cities VALUES ('Nowy Tomyśl');
INSERT INTO cities VALUES ('Nowy Wiśnicz');
INSERT INTO cities VALUES ('Nysa');
INSERT INTO cities VALUES ('Oborniki');
INSERT INTO cities VALUES ('Oborniki Śląskie');
INSERT INTO cities VALUES ('Obrzycko');
INSERT INTO cities VALUES ('Odolanów');
INSERT INTO cities VALUES ('Ogrodzieniec');
INSERT INTO cities VALUES ('Okonek');
INSERT INTO cities VALUES ('Olecko');
INSERT INTO cities VALUES ('Olesno');
INSERT INTO cities VALUES ('Oleszyce');
INSERT INTO cities VALUES ('Oleśnica');
INSERT INTO cities VALUES ('Olkusz');
INSERT INTO cities VALUES ('Olsztyn');
INSERT INTO cities VALUES ('Olsztynek');
INSERT INTO cities VALUES ('Olszyna');
INSERT INTO cities VALUES ('Oława');
INSERT INTO cities VALUES ('Opalenica');
INSERT INTO cities VALUES ('Opatów');
INSERT INTO cities VALUES ('Opoczno');
INSERT INTO cities VALUES ('Opole');
INSERT INTO cities VALUES ('Opole Lubelskie');
INSERT INTO cities VALUES ('Orneta');
INSERT INTO cities VALUES ('Orzesze');
INSERT INTO cities VALUES ('Orzysz');
INSERT INTO cities VALUES ('Osieczna');
INSERT INTO cities VALUES ('Osiek');
INSERT INTO cities VALUES ('Ostrołęka');
INSERT INTO cities VALUES ('Ostroróg');
INSERT INTO cities VALUES ('Ostrowiec Świętokrzyski');
INSERT INTO cities VALUES ('Ostróda');
INSERT INTO cities VALUES ('Ostrów Lubelski');
INSERT INTO cities VALUES ('Ostrów Mazowiecka');
INSERT INTO cities VALUES ('Ostrów Wielkopolski');
INSERT INTO cities VALUES ('Ostrzeszów');
INSERT INTO cities VALUES ('Ośno Lubuskie');
INSERT INTO cities VALUES ('Oświęcim');
INSERT INTO cities VALUES ('Otmuchów');
INSERT INTO cities VALUES ('Otwock');
INSERT INTO cities VALUES ('Ozimek');
INSERT INTO cities VALUES ('Ozorków');
INSERT INTO cities VALUES ('Ożarów');
INSERT INTO cities VALUES ('Ożarów Mazowiecki');
INSERT INTO cities VALUES ('Pabianice');
INSERT INTO cities VALUES ('Paczków');
INSERT INTO cities VALUES ('Pajęczno');
INSERT INTO cities VALUES ('Pakość');
INSERT INTO cities VALUES ('Parczew');
INSERT INTO cities VALUES ('Pasłęk');
INSERT INTO cities VALUES ('Pasym');
INSERT INTO cities VALUES ('Pelplin');
INSERT INTO cities VALUES ('Pełczyce');
INSERT INTO cities VALUES ('Piaseczno');
INSERT INTO cities VALUES ('Piaski');
INSERT INTO cities VALUES ('Piastów');
INSERT INTO cities VALUES ('Piechowice');
INSERT INTO cities VALUES ('Piekary Śląskie');
INSERT INTO cities VALUES ('Pieniężno');
INSERT INTO cities VALUES ('Pieńsk');
INSERT INTO cities VALUES ('Pieszyce');
INSERT INTO cities VALUES ('Pilawa');
INSERT INTO cities VALUES ('Pilica');
INSERT INTO cities VALUES ('Pilzno');
INSERT INTO cities VALUES ('Piła');
INSERT INTO cities VALUES ('Piława Górna');
INSERT INTO cities VALUES ('Pińczów');
INSERT INTO cities VALUES ('Pionki');
INSERT INTO cities VALUES ('Piotrków Kujawski');
INSERT INTO cities VALUES ('Piotrków Trybunalski');
INSERT INTO cities VALUES ('Pisz');
INSERT INTO cities VALUES ('Piwniczna-Zdrój');
INSERT INTO cities VALUES ('Pleszew');
INSERT INTO cities VALUES ('Płock');
INSERT INTO cities VALUES ('Płońsk');
INSERT INTO cities VALUES ('Płoty');
INSERT INTO cities VALUES ('Pniewy');
INSERT INTO cities VALUES ('Pobiedziska');
INSERT INTO cities VALUES ('Poddębice');
INSERT INTO cities VALUES ('Podkowa Leśna');
INSERT INTO cities VALUES ('Pogorzela');
INSERT INTO cities VALUES ('Polanica-Zdrój');
INSERT INTO cities VALUES ('Polanów');
INSERT INTO cities VALUES ('Police');
INSERT INTO cities VALUES ('Polkowice');
INSERT INTO cities VALUES ('Połaniec');
INSERT INTO cities VALUES ('Połczyn-Zdrój');
INSERT INTO cities VALUES ('Poniatowa');
INSERT INTO cities VALUES ('Poniec');
INSERT INTO cities VALUES ('Poręba');
INSERT INTO cities VALUES ('Poznań');
INSERT INTO cities VALUES ('Prabuty');
INSERT INTO cities VALUES ('Praszka');
INSERT INTO cities VALUES ('Prochowice');
INSERT INTO cities VALUES ('Proszowice');
INSERT INTO cities VALUES ('Prószków');
INSERT INTO cities VALUES ('Pruchnik');
INSERT INTO cities VALUES ('Prudnik');
INSERT INTO cities VALUES ('Prusice');
INSERT INTO cities VALUES ('Pruszcz Gdański');
INSERT INTO cities VALUES ('Pruszków');
INSERT INTO cities VALUES ('Przasnysz');
INSERT INTO cities VALUES ('Przecław');
INSERT INTO cities VALUES ('Przedbórz');
INSERT INTO cities VALUES ('Przedecz');
INSERT INTO cities VALUES ('Przemków');
INSERT INTO cities VALUES ('Przemyśl');
INSERT INTO cities VALUES ('Przeworsk');
INSERT INTO cities VALUES ('Przysucha');
INSERT INTO cities VALUES ('Pszczyna');
INSERT INTO cities VALUES ('Pszów');
INSERT INTO cities VALUES ('Puck');
INSERT INTO cities VALUES ('Puławy');
INSERT INTO cities VALUES ('Pułtusk');
INSERT INTO cities VALUES ('Puszczykowo');
INSERT INTO cities VALUES ('Pyrzyce');
INSERT INTO cities VALUES ('Pyskowice');
INSERT INTO cities VALUES ('Pyzdry');
INSERT INTO cities VALUES ('Rabka-Zdrój');
INSERT INTO cities VALUES ('Raciąż');
INSERT INTO cities VALUES ('Racibórz');
INSERT INTO cities VALUES ('Radków');
INSERT INTO cities VALUES ('Radlin');
INSERT INTO cities VALUES ('Radłów');
INSERT INTO cities VALUES ('Radom');
INSERT INTO cities VALUES ('Radomsko');
INSERT INTO cities VALUES ('Radomyśl Wielki');
INSERT INTO cities VALUES ('Radymno');
INSERT INTO cities VALUES ('Radziejów');
INSERT INTO cities VALUES ('Radzionków');
INSERT INTO cities VALUES ('Radzymin');
INSERT INTO cities VALUES ('Radzyń Chełmiński');
INSERT INTO cities VALUES ('Radzyń Podlaski');
INSERT INTO cities VALUES ('Rajgród');
INSERT INTO cities VALUES ('Rakoniewice');
INSERT INTO cities VALUES ('Raszków');
INSERT INTO cities VALUES ('Rawa Mazowiecka');
INSERT INTO cities VALUES ('Rawicz');
INSERT INTO cities VALUES ('Recz');
INSERT INTO cities VALUES ('Reda');
INSERT INTO cities VALUES ('Rejowiec Fabryczny');
INSERT INTO cities VALUES ('Resko');
INSERT INTO cities VALUES ('Reszel');
INSERT INTO cities VALUES ('Rogoźno');
INSERT INTO cities VALUES ('Ropczyce');
INSERT INTO cities VALUES ('Różan');
INSERT INTO cities VALUES ('Ruciane-Nida');
INSERT INTO cities VALUES ('Ruda Śląska');
INSERT INTO cities VALUES ('Rudnik nad');
INSERT INTO cities VALUES ('Sanem');
INSERT INTO cities VALUES ('Rumia');
INSERT INTO cities VALUES ('Rybnik');
INSERT INTO cities VALUES ('Rychwał');
INSERT INTO cities VALUES ('Rydułtowy');
INSERT INTO cities VALUES ('Rydzyna');
INSERT INTO cities VALUES ('Ryglice');
INSERT INTO cities VALUES ('Ryki');
INSERT INTO cities VALUES ('Rymanów');
INSERT INTO cities VALUES ('Ryn');
INSERT INTO cities VALUES ('Rypin');
INSERT INTO cities VALUES ('Rzepin');
INSERT INTO cities VALUES ('Rzeszów');
INSERT INTO cities VALUES ('Rzgów');
INSERT INTO cities VALUES ('Sandomierz');
INSERT INTO cities VALUES ('Sanok');
INSERT INTO cities VALUES ('Sejny');
INSERT INTO cities VALUES ('Serock');
INSERT INTO cities VALUES ('Sędziszów');
INSERT INTO cities VALUES ('Sędziszów Małopolski');
INSERT INTO cities VALUES ('Sępopol');
INSERT INTO cities VALUES ('Sępólno Krajeńskie');
INSERT INTO cities VALUES ('Sianów');
INSERT INTO cities VALUES ('Siechnice');
INSERT INTO cities VALUES ('Siedlce');
INSERT INTO cities VALUES ('Siedliszcze');
INSERT INTO cities VALUES ('Siemianowice Śląskie');
INSERT INTO cities VALUES ('Siemiatycze');
INSERT INTO cities VALUES ('Sieniawa');
INSERT INTO cities VALUES ('Sieradz');
INSERT INTO cities VALUES ('Sieraków');
INSERT INTO cities VALUES ('Sierpc');
INSERT INTO cities VALUES ('Siewierz');
INSERT INTO cities VALUES ('Skalbmierz');
INSERT INTO cities VALUES ('Skała');
INSERT INTO cities VALUES ('Skarszewy');
INSERT INTO cities VALUES ('Skaryszew');
INSERT INTO cities VALUES ('Skarżysko-Kamienna');
INSERT INTO cities VALUES ('Skawina');
INSERT INTO cities VALUES ('Skępe');
INSERT INTO cities VALUES ('Skierniewice');
INSERT INTO cities VALUES ('Skoczów');
INSERT INTO cities VALUES ('Skoki');
INSERT INTO cities VALUES ('Skórcz');
INSERT INTO cities VALUES ('Skwierzyna');
INSERT INTO cities VALUES ('Sława');
INSERT INTO cities VALUES ('Sławków');
INSERT INTO cities VALUES ('Sławno');
INSERT INTO cities VALUES ('Słomniki');
INSERT INTO cities VALUES ('Słubice');
INSERT INTO cities VALUES ('Słupca');
INSERT INTO cities VALUES ('Słupsk');
INSERT INTO cities VALUES ('Sobótka');
INSERT INTO cities VALUES ('Sochaczew');
INSERT INTO cities VALUES ('Sokołów Małopolski');
INSERT INTO cities VALUES ('Sokołów Podlaski');
INSERT INTO cities VALUES ('Sokółka');
INSERT INTO cities VALUES ('Solec Kujawski');
INSERT INTO cities VALUES ('Sompolno');
INSERT INTO cities VALUES ('Sopot');
INSERT INTO cities VALUES ('Sosnowiec');
INSERT INTO cities VALUES ('Sośnicowice');
INSERT INTO cities VALUES ('Stalowa Wola');
INSERT INTO cities VALUES ('Starachowice');
INSERT INTO cities VALUES ('Stargard');
INSERT INTO cities VALUES ('Starogard Gdański');
INSERT INTO cities VALUES ('Stary Sącz');
INSERT INTO cities VALUES ('Staszów');
INSERT INTO cities VALUES ('Stawiski');
INSERT INTO cities VALUES ('Stawiszyn');
INSERT INTO cities VALUES ('Stąporków');
INSERT INTO cities VALUES ('Stepnica');
INSERT INTO cities VALUES ('Stęszew');
INSERT INTO cities VALUES ('Stoczek Łukowski');
INSERT INTO cities VALUES ('Stopnica');
INSERT INTO cities VALUES ('Stronie Śląskie');
INSERT INTO cities VALUES ('Strumień');
INSERT INTO cities VALUES ('Stryków');
INSERT INTO cities VALUES ('Strzegom');
INSERT INTO cities VALUES ('Strzelce Krajeńskie');
INSERT INTO cities VALUES ('Strzelce Opolskie');
INSERT INTO cities VALUES ('Strzelin');
INSERT INTO cities VALUES ('Strzelno');
INSERT INTO cities VALUES ('Strzyżów');
INSERT INTO cities VALUES ('Sucha Beskidzka');
INSERT INTO cities VALUES ('Suchań');
INSERT INTO cities VALUES ('Suchedniów');
INSERT INTO cities VALUES ('Suchowola');
INSERT INTO cities VALUES ('Sulechów');
INSERT INTO cities VALUES ('Sulejów');
INSERT INTO cities VALUES ('Sulejówek');
INSERT INTO cities VALUES ('Sulęcin');
INSERT INTO cities VALUES ('Sulmierzyce');
INSERT INTO cities VALUES ('Sułkowice');
INSERT INTO cities VALUES ('Supraśl');
INSERT INTO cities VALUES ('Suraż');
INSERT INTO cities VALUES ('Susz');
INSERT INTO cities VALUES ('Suwałki');
INSERT INTO cities VALUES ('Swarzędz');
INSERT INTO cities VALUES ('Syców');
INSERT INTO cities VALUES ('Szadek');
INSERT INTO cities VALUES ('Szamocin');
INSERT INTO cities VALUES ('Szamotuły');
INSERT INTO cities VALUES ('Szczawnica');
INSERT INTO cities VALUES ('Szczawno-Zdrój');
INSERT INTO cities VALUES ('Szczebrzeszyn');
INSERT INTO cities VALUES ('Szczecin');
INSERT INTO cities VALUES ('Szczecinek');
INSERT INTO cities VALUES ('Szczekociny');
INSERT INTO cities VALUES ('Szczucin');
INSERT INTO cities VALUES ('Szczuczyn');
INSERT INTO cities VALUES ('Szczyrk');
INSERT INTO cities VALUES ('Szczytna');
INSERT INTO cities VALUES ('Szczytno');
INSERT INTO cities VALUES ('Szepietowo');
INSERT INTO cities VALUES ('Szklarska Poręba');
INSERT INTO cities VALUES ('Szlichtyngowa');
INSERT INTO cities VALUES ('Szprotawa');
INSERT INTO cities VALUES ('Sztum');
INSERT INTO cities VALUES ('Szubin');
INSERT INTO cities VALUES ('Szydłowiec');
INSERT INTO cities VALUES ('Ścinawa');
INSERT INTO cities VALUES ('Ślesin');
INSERT INTO cities VALUES ('Śmigiel');
INSERT INTO cities VALUES ('Śrem');
INSERT INTO cities VALUES ('Środa Śląska');
INSERT INTO cities VALUES ('Środa Wielkopolska');
INSERT INTO cities VALUES ('Świątniki Górne');
INSERT INTO cities VALUES ('Świdnica');
INSERT INTO cities VALUES ('Świdnik');
INSERT INTO cities VALUES ('Świdwin');
INSERT INTO cities VALUES ('Świebodzice');
INSERT INTO cities VALUES ('Świebodzin');
INSERT INTO cities VALUES ('Świecie');
INSERT INTO cities VALUES ('Świeradów-Zdrój');
INSERT INTO cities VALUES ('Świerzawa');
INSERT INTO cities VALUES ('Świętochłowice');
INSERT INTO cities VALUES ('Świnoujście');
INSERT INTO cities VALUES ('Tarczyn');
INSERT INTO cities VALUES ('Tarnobrzeg');
INSERT INTO cities VALUES ('Tarnogród');
INSERT INTO cities VALUES ('Tarnowskie Góry');
INSERT INTO cities VALUES ('Tarnów');
INSERT INTO cities VALUES ('Tczew');
INSERT INTO cities VALUES ('Terespol');
INSERT INTO cities VALUES ('Tłuszcz');
INSERT INTO cities VALUES ('Tolkmicko');
INSERT INTO cities VALUES ('Tomaszów Lubelski');
INSERT INTO cities VALUES ('Tomaszów Mazowiecki');
INSERT INTO cities VALUES ('Toruń');
INSERT INTO cities VALUES ('Torzym');
INSERT INTO cities VALUES ('Toszek');
INSERT INTO cities VALUES ('Trzcianka');
INSERT INTO cities VALUES ('Trzciel');
INSERT INTO cities VALUES ('Trzcińsko-Zdrój');
INSERT INTO cities VALUES ('Trzebiatów');
INSERT INTO cities VALUES ('Trzebinia');
INSERT INTO cities VALUES ('Trzebnica');
INSERT INTO cities VALUES ('Trzemeszno');
INSERT INTO cities VALUES ('Tuchola');
INSERT INTO cities VALUES ('Tuchów');
INSERT INTO cities VALUES ('Tuczno');
INSERT INTO cities VALUES ('Tuliszków');
INSERT INTO cities VALUES ('Turek');
INSERT INTO cities VALUES ('Tuszyn');
INSERT INTO cities VALUES ('Twardogóra');
INSERT INTO cities VALUES ('Tychowo');
INSERT INTO cities VALUES ('Tychy');
INSERT INTO cities VALUES ('Tyczyn');
INSERT INTO cities VALUES ('Tykocin');
INSERT INTO cities VALUES ('Tyszowce');
INSERT INTO cities VALUES ('Ujazd');
INSERT INTO cities VALUES ('Ujście');
INSERT INTO cities VALUES ('Ulanów');
INSERT INTO cities VALUES ('Uniejów');
INSERT INTO cities VALUES ('Urzędów');
INSERT INTO cities VALUES ('Ustka');
INSERT INTO cities VALUES ('Ustroń');
INSERT INTO cities VALUES ('Ustrzyki Dolne');
INSERT INTO cities VALUES ('Wadowice');
INSERT INTO cities VALUES ('Wałbrzych');
INSERT INTO cities VALUES ('Wałcz');
INSERT INTO cities VALUES ('Warka');
INSERT INTO cities VALUES ('Warta');
INSERT INTO cities VALUES ('Wasilków');
INSERT INTO cities VALUES ('Wąbrzeźno');
INSERT INTO cities VALUES ('Wąchock');
INSERT INTO cities VALUES ('Wągrowiec');
INSERT INTO cities VALUES ('Wąsosz');
INSERT INTO cities VALUES ('Wejherowo');
INSERT INTO cities VALUES ('Węgliniec');
INSERT INTO cities VALUES ('Węgorzewo');
INSERT INTO cities VALUES ('Węgorzyno');
INSERT INTO cities VALUES ('Węgrów');
INSERT INTO cities VALUES ('Wiązów');
INSERT INTO cities VALUES ('Wieleń');
INSERT INTO cities VALUES ('Wielichowo');
INSERT INTO cities VALUES ('Wieliczka');
INSERT INTO cities VALUES ('Wieluń');
INSERT INTO cities VALUES ('Wieruszów');
INSERT INTO cities VALUES ('Więcbork');
INSERT INTO cities VALUES ('Wilamowice');
INSERT INTO cities VALUES ('Witkowo');
INSERT INTO cities VALUES ('Witnica');
INSERT INTO cities VALUES ('Wleń');
INSERT INTO cities VALUES ('Władysławowo');
INSERT INTO cities VALUES ('Włocławek');
INSERT INTO cities VALUES ('Włodawa');
INSERT INTO cities VALUES ('Włoszczowa');
INSERT INTO cities VALUES ('Wodzisław Śląski');
INSERT INTO cities VALUES ('Wojcieszów');
INSERT INTO cities VALUES ('Wojkowice');
INSERT INTO cities VALUES ('Wojnicz');
INSERT INTO cities VALUES ('Wolbórz');
INSERT INTO cities VALUES ('Wolbrom');
INSERT INTO cities VALUES ('Wolin');
INSERT INTO cities VALUES ('Wolsztyn');
INSERT INTO cities VALUES ('Wołczyn');
INSERT INTO cities VALUES ('Wołomin');
INSERT INTO cities VALUES ('Wołów');
INSERT INTO cities VALUES ('Woźniki');
INSERT INTO cities VALUES ('Wrocław');
INSERT INTO cities VALUES ('Wronki');
INSERT INTO cities VALUES ('Września');
INSERT INTO cities VALUES ('Wschowa');
INSERT INTO cities VALUES ('Wyrzysk');
INSERT INTO cities VALUES ('Wysoka');
INSERT INTO cities VALUES ('Wysokie Mazowieckie');
INSERT INTO cities VALUES ('Wyszków');
INSERT INTO cities VALUES ('Wyszogród');
INSERT INTO cities VALUES ('Wyśmierzyce');
INSERT INTO cities VALUES ('Zabłudów');
INSERT INTO cities VALUES ('Zabrze');
INSERT INTO cities VALUES ('Zagórów');
INSERT INTO cities VALUES ('Zagórz');
INSERT INTO cities VALUES ('Zakliczyn');
INSERT INTO cities VALUES ('Zaklików');
INSERT INTO cities VALUES ('Zakopane');
INSERT INTO cities VALUES ('Zakroczym');
INSERT INTO cities VALUES ('Zalewo');
INSERT INTO cities VALUES ('Zambrów');
INSERT INTO cities VALUES ('Zamość');
INSERT INTO cities VALUES ('Zator');
INSERT INTO cities VALUES ('Zawadzkie');
INSERT INTO cities VALUES ('Zawichost');
INSERT INTO cities VALUES ('Zawidów');
INSERT INTO cities VALUES ('Zawiercie');
INSERT INTO cities VALUES ('Ząbki');
INSERT INTO cities VALUES ('Ząbkowice Śląskie');
INSERT INTO cities VALUES ('Zbąszynek');
INSERT INTO cities VALUES ('Zbąszyń');
INSERT INTO cities VALUES ('Zduny');
INSERT INTO cities VALUES ('Zduńska Wola');
INSERT INTO cities VALUES ('Zdzieszowice');
INSERT INTO cities VALUES ('Zelów');
INSERT INTO cities VALUES ('Zgierz');
INSERT INTO cities VALUES ('Zgorzelec');
INSERT INTO cities VALUES ('Zielona Góra');
INSERT INTO cities VALUES ('Zielonka');
INSERT INTO cities VALUES ('Ziębice');
INSERT INTO cities VALUES ('Złocieniec');
INSERT INTO cities VALUES ('Złoczew');
INSERT INTO cities VALUES ('Złotoryja');
INSERT INTO cities VALUES ('Złotów');
INSERT INTO cities VALUES ('Złoty Stok');
INSERT INTO cities VALUES ('Zwierzyniec');
INSERT INTO cities VALUES ('Zwoleń');
INSERT INTO cities VALUES ('Żabno');
INSERT INTO cities VALUES ('Żagań');
INSERT INTO cities VALUES ('Żarki');
INSERT INTO cities VALUES ('Żarów');
INSERT INTO cities VALUES ('Żary');
INSERT INTO cities VALUES ('Żelechów');
INSERT INTO cities VALUES ('Żerków');
INSERT INTO cities VALUES ('Żmigród');
INSERT INTO cities VALUES ('Żnin');
INSERT INTO cities VALUES ('Żory');
INSERT INTO cities VALUES ('Żukowo');
INSERT INTO cities VALUES ('Żuromin');
INSERT INTO cities VALUES ('Żychlin');
INSERT INTO cities VALUES ('Żyrardów');
INSERT INTO cities VALUES ('Żywiec');

