DROP DATABASE albalbcardb;

CREATE SCHEMA IF NOT EXISTS albalbcardb;

USE albalbcardb; 

CREATE TABLE IF NOT EXISTS roles(
	role_id INT NOT NULL PRIMARY KEY,
    user_role VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
	id int not null auto_increment primary key,
	login VARCHAR(100) NOT NULL unique,
    password VARCHAR(128) NOT NULL,
	phone_number VARCHAR(100),
    enabled bit not null
);

CREATE TABLE IF NOT EXISTS users_roles(
	role_id INT NOT NULL,
    user_id int NOT NULL,
	FOREIGN KEY (role_id) REFERENCES roles(role_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS cities(
	id int auto_increment not null primary key,
    city_name VARCHAR(100) NOT NULL 
);

CREATE TABLE IF NOT EXISTS rides(
	ride_id int auto_increment not null primary key,
    driver int,
    seats int,
    ride_date datetime,
    price int,
    FOREIGN KEY (driver) REFERENCES users(id)
);
   
CREATE TABLE IF NOT EXISTS rides_cities(
	id int auto_increment not null primary key,
    ride_id int,
    city_id int,
    price double,
    delay int,
    people_in_car int,
    FOREIGN KEY (ride_id) REFERENCES rides(ride_id),
    FOREIGN KEY (city_id) REFERENCES cities(id)
);


CREATE TABLE IF NOT EXISTS rides_users(
	id int auto_increment not null primary key,
    ride_id int,
    user_id int,
    from_city int,
    to_city int,
    FOREIGN KEY (ride_id) REFERENCES rides(ride_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (from_city) REFERENCES cities(id),
    FOREIGN KEY (to_city) REFERENCES cities(id)
);
    
INSERT INTO roles VALUES (1,'admin');
INSERT INTO roles VALUES (2,'user');
INSERT INTO users VALUES (1,'jop','123','231213123',1);
INSERT INTO users VALUES (2,'user1','123','231213123',1);
INSERT INTO users_roles VALUES (1,'1');
INSERT INTO users_roles VALUES (2,'2');



INSERT INTO cities (city_name) VALUES ('Warszawa');
INSERT INTO cities (city_name) VALUES ('Aleksandrów Kujawski');
INSERT INTO cities (city_name) VALUES ('Aleksandrów Łódzki');
INSERT INTO cities (city_name) VALUES ('Alwernia');
INSERT INTO cities (city_name) VALUES ('Andrychów');
INSERT INTO cities (city_name) VALUES ('Annopol');
INSERT INTO cities (city_name) VALUES ('Augustów');
INSERT INTO cities (city_name) VALUES ('Babimost');
INSERT INTO cities (city_name) VALUES ('Baborów');
INSERT INTO cities (city_name) VALUES ('Baranów Sandomierski');
INSERT INTO cities (city_name) VALUES ('Barcin');
INSERT INTO cities (city_name) VALUES ('Barczewo');
INSERT INTO cities (city_name) VALUES ('Bardo');
INSERT INTO cities (city_name) VALUES ('Barlinek');
INSERT INTO cities (city_name) VALUES ('Bartoszyce');
INSERT INTO cities (city_name) VALUES ('Barwice');
INSERT INTO cities (city_name) VALUES ('Bełchatów');
INSERT INTO cities (city_name) VALUES ('Bełżyce');
INSERT INTO cities (city_name) VALUES ('Będzin');
INSERT INTO cities (city_name) VALUES ('Biała');
INSERT INTO cities (city_name) VALUES ('Biała Piska');
INSERT INTO cities (city_name) VALUES ('Biała Podlaska');
INSERT INTO cities (city_name) VALUES ('Biała Rawska');
INSERT INTO cities (city_name) VALUES ('Białobrzegi');
INSERT INTO cities (city_name) VALUES ('Białogard');
INSERT INTO cities (city_name) VALUES ('Biały Bór');
INSERT INTO cities (city_name) VALUES ('Białystok');
INSERT INTO cities (city_name) VALUES ('Biecz');
INSERT INTO cities (city_name) VALUES ('Bielawa');
INSERT INTO cities (city_name) VALUES ('Bielsk Podlaski');
INSERT INTO cities (city_name) VALUES ('Bielsko-Biała');
INSERT INTO cities (city_name) VALUES ('Bieruń');
INSERT INTO cities (city_name) VALUES ('Bierutów');
INSERT INTO cities (city_name) VALUES ('Bieżuń');
INSERT INTO cities (city_name) VALUES ('Biłgoraj');
INSERT INTO cities (city_name) VALUES ('Biskupiec');
INSERT INTO cities (city_name) VALUES ('Bisztynek');
INSERT INTO cities (city_name) VALUES ('Blachownia');
INSERT INTO cities (city_name) VALUES ('Błaszki');
INSERT INTO cities (city_name) VALUES ('Błażowa');
INSERT INTO cities (city_name) VALUES ('Błonie');
INSERT INTO cities (city_name) VALUES ('Bobolice');
INSERT INTO cities (city_name) VALUES ('Bobowa');
INSERT INTO cities (city_name) VALUES ('Bochnia');
INSERT INTO cities (city_name) VALUES ('Bodzentyn');
INSERT INTO cities (city_name) VALUES ('Bogatynia');
INSERT INTO cities (city_name) VALUES ('Boguchwała');
INSERT INTO cities (city_name) VALUES ('Boguszów-Gorce');
INSERT INTO cities (city_name) VALUES ('Bojanowo');
INSERT INTO cities (city_name) VALUES ('Bolesławiec');
INSERT INTO cities (city_name) VALUES ('Bolków');
INSERT INTO cities (city_name) VALUES ('Borek Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Borne Sulinowo');
INSERT INTO cities (city_name) VALUES ('Braniewo');
INSERT INTO cities (city_name) VALUES ('Brańsk');
INSERT INTO cities (city_name) VALUES ('Brodnica');
INSERT INTO cities (city_name) VALUES ('Brok');
INSERT INTO cities (city_name) VALUES ('Brusy');
INSERT INTO cities (city_name) VALUES ('Brwinów');
INSERT INTO cities (city_name) VALUES ('Brzeg');
INSERT INTO cities (city_name) VALUES ('Brzeg Dolny');
INSERT INTO cities (city_name) VALUES ('Brzesko');
INSERT INTO cities (city_name) VALUES ('Brzeszcze');
INSERT INTO cities (city_name) VALUES ('Brześć Kujawski');
INSERT INTO cities (city_name) VALUES ('Brzeziny');
INSERT INTO cities (city_name) VALUES ('Brzostek');
INSERT INTO cities (city_name) VALUES ('Brzozów');
INSERT INTO cities (city_name) VALUES ('Buk');
INSERT INTO cities (city_name) VALUES ('Bukowno');
INSERT INTO cities (city_name) VALUES ('Busko-Zdrój');
INSERT INTO cities (city_name) VALUES ('Bychawa');
INSERT INTO cities (city_name) VALUES ('Byczyna');
INSERT INTO cities (city_name) VALUES ('Bydgoszcz');
INSERT INTO cities (city_name) VALUES ('Bystrzyca Kłodzka');
INSERT INTO cities (city_name) VALUES ('Bytom');
INSERT INTO cities (city_name) VALUES ('Bytom Odrzański');
INSERT INTO cities (city_name) VALUES ('Bytów');
INSERT INTO cities (city_name) VALUES ('Cedynia');
INSERT INTO cities (city_name) VALUES ('Chełm');
INSERT INTO cities (city_name) VALUES ('Chełmek');
INSERT INTO cities (city_name) VALUES ('Chełmno');
INSERT INTO cities (city_name) VALUES ('Chełmża');
INSERT INTO cities (city_name) VALUES ('Chęciny');
INSERT INTO cities (city_name) VALUES ('Chmielnik');
INSERT INTO cities (city_name) VALUES ('Chocianów');
INSERT INTO cities (city_name) VALUES ('Chociwel');
INSERT INTO cities (city_name) VALUES ('Chocz');
INSERT INTO cities (city_name) VALUES ('Chodecz');
INSERT INTO cities (city_name) VALUES ('Chodzież');
INSERT INTO cities (city_name) VALUES ('Chojna');
INSERT INTO cities (city_name) VALUES ('Chojnice');
INSERT INTO cities (city_name) VALUES ('Chojnów');
INSERT INTO cities (city_name) VALUES ('Choroszcz');
INSERT INTO cities (city_name) VALUES ('Chorzele');
INSERT INTO cities (city_name) VALUES ('Chorzów');
INSERT INTO cities (city_name) VALUES ('Choszczno');
INSERT INTO cities (city_name) VALUES ('Chrzanów');
INSERT INTO cities (city_name) VALUES ('Ciechanowiec');
INSERT INTO cities (city_name) VALUES ('Ciechanów');
INSERT INTO cities (city_name) VALUES ('Ciechocinek');
INSERT INTO cities (city_name) VALUES ('Cieszanów');
INSERT INTO cities (city_name) VALUES ('Cieszyn');
INSERT INTO cities (city_name) VALUES ('Ciężkowice');
INSERT INTO cities (city_name) VALUES ('Cybinka');
INSERT INTO cities (city_name) VALUES ('Czaplinek');
INSERT INTO cities (city_name) VALUES ('Czarna Białostocka');
INSERT INTO cities (city_name) VALUES ('Czarna Woda');
INSERT INTO cities (city_name) VALUES ('Czarne');
INSERT INTO cities (city_name) VALUES ('Czarnków');
INSERT INTO cities (city_name) VALUES ('Czchów');
INSERT INTO cities (city_name) VALUES ('Czechowice-Dziedzice');
INSERT INTO cities (city_name) VALUES ('Czeladź');
INSERT INTO cities (city_name) VALUES ('Czempiń');
INSERT INTO cities (city_name) VALUES ('Czerniejewo');
INSERT INTO cities (city_name) VALUES ('Czersk');
INSERT INTO cities (city_name) VALUES ('Czerwieńsk');
INSERT INTO cities (city_name) VALUES ('Czerwionka-Leszczyny');
INSERT INTO cities (city_name) VALUES ('Częstochowa');
INSERT INTO cities (city_name) VALUES ('Człopa');
INSERT INTO cities (city_name) VALUES ('Człuchów');
INSERT INTO cities (city_name) VALUES ('Czyżew');
INSERT INTO cities (city_name) VALUES ('Ćmielów');
INSERT INTO cities (city_name) VALUES ('Daleszyce');
INSERT INTO cities (city_name) VALUES ('Darłowo');
INSERT INTO cities (city_name) VALUES ('Dąbie');
INSERT INTO cities (city_name) VALUES ('Dąbrowa Białostocka');
INSERT INTO cities (city_name) VALUES ('Dąbrowa Górnicza');
INSERT INTO cities (city_name) VALUES ('Dąbrowa Tarnowska');
INSERT INTO cities (city_name) VALUES ('Debrzno');
INSERT INTO cities (city_name) VALUES ('Dębica');
INSERT INTO cities (city_name) VALUES ('Dęblin');
INSERT INTO cities (city_name) VALUES ('Dębno');
INSERT INTO cities (city_name) VALUES ('Dobczyce');
INSERT INTO cities (city_name) VALUES ('Dobiegniew');
INSERT INTO cities (city_name) VALUES ('Dobra');
INSERT INTO cities (city_name) VALUES ('Dobre Miasto');
INSERT INTO cities (city_name) VALUES ('Dobrodzień');
INSERT INTO cities (city_name) VALUES ('Dobrzany');
INSERT INTO cities (city_name) VALUES ('Dobrzyca');
INSERT INTO cities (city_name) VALUES ('Dobrzyń nad');
INSERT INTO cities (city_name) VALUES ('Wisłą');
INSERT INTO cities (city_name) VALUES ('Dolsk');
INSERT INTO cities (city_name) VALUES ('Drawno');
INSERT INTO cities (city_name) VALUES ('Drawsko Pomorskie');
INSERT INTO cities (city_name) VALUES ('Drezdenko');
INSERT INTO cities (city_name) VALUES ('Drobin');
INSERT INTO cities (city_name) VALUES ('Drohiczyn');
INSERT INTO cities (city_name) VALUES ('Drzewica');
INSERT INTO cities (city_name) VALUES ('Dukla');
INSERT INTO cities (city_name) VALUES ('Duszniki-Zdrój');
INSERT INTO cities (city_name) VALUES ('Dynów');
INSERT INTO cities (city_name) VALUES ('Działdowo');
INSERT INTO cities (city_name) VALUES ('Działoszyce');
INSERT INTO cities (city_name) VALUES ('Działoszyn');
INSERT INTO cities (city_name) VALUES ('Dzierzgoń');
INSERT INTO cities (city_name) VALUES ('Dzierżoniów');
INSERT INTO cities (city_name) VALUES ('Dziwnów');
INSERT INTO cities (city_name) VALUES ('Elbląg');
INSERT INTO cities (city_name) VALUES ('Ełk');
INSERT INTO cities (city_name) VALUES ('Frampol');
INSERT INTO cities (city_name) VALUES ('Frombork');
INSERT INTO cities (city_name) VALUES ('Garwolin');
INSERT INTO cities (city_name) VALUES ('Gąbin');
INSERT INTO cities (city_name) VALUES ('Gdańsk');
INSERT INTO cities (city_name) VALUES ('Gdynia');
INSERT INTO cities (city_name) VALUES ('Giżycko');
INSERT INTO cities (city_name) VALUES ('Glinojeck');
INSERT INTO cities (city_name) VALUES ('Gliwice');
INSERT INTO cities (city_name) VALUES ('Głogów');
INSERT INTO cities (city_name) VALUES ('Głogów Małopolski');
INSERT INTO cities (city_name) VALUES ('Głogówek');
INSERT INTO cities (city_name) VALUES ('Głowno');
INSERT INTO cities (city_name) VALUES ('Głubczyce');
INSERT INTO cities (city_name) VALUES ('Głuchołazy');
INSERT INTO cities (city_name) VALUES ('Głuszyca');
INSERT INTO cities (city_name) VALUES ('Gniew');
INSERT INTO cities (city_name) VALUES ('Gniewkowo');
INSERT INTO cities (city_name) VALUES ('Gniezno');
INSERT INTO cities (city_name) VALUES ('Gogolin');
INSERT INTO cities (city_name) VALUES ('Golczewo');
INSERT INTO cities (city_name) VALUES ('Goleniów');
INSERT INTO cities (city_name) VALUES ('Golina');
INSERT INTO cities (city_name) VALUES ('Golub-Dobrzyń');
INSERT INTO cities (city_name) VALUES ('Gołańcz');
INSERT INTO cities (city_name) VALUES ('Gołdap');
INSERT INTO cities (city_name) VALUES ('Goniądz');
INSERT INTO cities (city_name) VALUES ('Gorlice');
INSERT INTO cities (city_name) VALUES ('Gorzów Śląski');
INSERT INTO cities (city_name) VALUES ('Gorzów Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Gostynin');
INSERT INTO cities (city_name) VALUES ('Gostyń');
INSERT INTO cities (city_name) VALUES ('Gościno');
INSERT INTO cities (city_name) VALUES ('Gozdnica');
INSERT INTO cities (city_name) VALUES ('Góra');
INSERT INTO cities (city_name) VALUES ('Góra Kalwaria');
INSERT INTO cities (city_name) VALUES ('Górowo Iławeckie');
INSERT INTO cities (city_name) VALUES ('Górzno');
INSERT INTO cities (city_name) VALUES ('Grabów nad');
INSERT INTO cities (city_name) VALUES ('Prosną');
INSERT INTO cities (city_name) VALUES ('Grajewo');
INSERT INTO cities (city_name) VALUES ('Grodków');
INSERT INTO cities (city_name) VALUES ('Grodzisk Mazowiecki');
INSERT INTO cities (city_name) VALUES ('Grodzisk Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Grójec');
INSERT INTO cities (city_name) VALUES ('Grudziądz');
INSERT INTO cities (city_name) VALUES ('Grybów');
INSERT INTO cities (city_name) VALUES ('Gryfice');
INSERT INTO cities (city_name) VALUES ('Gryfino');
INSERT INTO cities (city_name) VALUES ('Gryfów Śląski');
INSERT INTO cities (city_name) VALUES ('Gubin');
INSERT INTO cities (city_name) VALUES ('Hajnówka');
INSERT INTO cities (city_name) VALUES ('Halinów');
INSERT INTO cities (city_name) VALUES ('Hel');
INSERT INTO cities (city_name) VALUES ('Hrubieszów');
INSERT INTO cities (city_name) VALUES ('Iława');
INSERT INTO cities (city_name) VALUES ('Iłowa');
INSERT INTO cities (city_name) VALUES ('Iłża');
INSERT INTO cities (city_name) VALUES ('Imielin');
INSERT INTO cities (city_name) VALUES ('Inowrocław');
INSERT INTO cities (city_name) VALUES ('Ińsko');
INSERT INTO cities (city_name) VALUES ('Iwonicz-Zdrój');
INSERT INTO cities (city_name) VALUES ('Izbica Kujawska');
INSERT INTO cities (city_name) VALUES ('Jabłonowo Pomorskie');
INSERT INTO cities (city_name) VALUES ('Janikowo');
INSERT INTO cities (city_name) VALUES ('Janowiec Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Janów Lubelski');
INSERT INTO cities (city_name) VALUES ('Jaraczewo');
INSERT INTO cities (city_name) VALUES ('Jarocin');
INSERT INTO cities (city_name) VALUES ('Jarosław');
INSERT INTO cities (city_name) VALUES ('Jasień');
INSERT INTO cities (city_name) VALUES ('Jasło');
INSERT INTO cities (city_name) VALUES ('Jastarnia');
INSERT INTO cities (city_name) VALUES ('Jastrowie');
INSERT INTO cities (city_name) VALUES ('Jastrzębie-Zdrój');
INSERT INTO cities (city_name) VALUES ('Jawor');
INSERT INTO cities (city_name) VALUES ('Jaworzno');
INSERT INTO cities (city_name) VALUES ('Jaworzyna Śląska');
INSERT INTO cities (city_name) VALUES ('Jedlicze');
INSERT INTO cities (city_name) VALUES ('Jedlina-Zdrój');
INSERT INTO cities (city_name) VALUES ('Jedwabne');
INSERT INTO cities (city_name) VALUES ('Jelcz-Laskowice');
INSERT INTO cities (city_name) VALUES ('Jelenia Góra');
INSERT INTO cities (city_name) VALUES ('Jeziorany');
INSERT INTO cities (city_name) VALUES ('Jędrzejów');
INSERT INTO cities (city_name) VALUES ('Jordanów');
INSERT INTO cities (city_name) VALUES ('Józefów');
INSERT INTO cities (city_name) VALUES ('Jutrosin');
INSERT INTO cities (city_name) VALUES ('Kalety');
INSERT INTO cities (city_name) VALUES ('Kalisz');
INSERT INTO cities (city_name) VALUES ('Kalisz Pomorski');
INSERT INTO cities (city_name) VALUES ('Kalwaria Zebrzydowska');
INSERT INTO cities (city_name) VALUES ('Kałuszyn');
INSERT INTO cities (city_name) VALUES ('Kamienna Góra');
INSERT INTO cities (city_name) VALUES ('Kamień Krajeński');
INSERT INTO cities (city_name) VALUES ('Kamień Pomorski');
INSERT INTO cities (city_name) VALUES ('Kamieńsk');
INSERT INTO cities (city_name) VALUES ('Kańczuga');
INSERT INTO cities (city_name) VALUES ('Karczew');
INSERT INTO cities (city_name) VALUES ('Kargowa');
INSERT INTO cities (city_name) VALUES ('Karlino');
INSERT INTO cities (city_name) VALUES ('Karpacz');
INSERT INTO cities (city_name) VALUES ('Kartuzy');
INSERT INTO cities (city_name) VALUES ('Katowice');
INSERT INTO cities (city_name) VALUES ('Kazimierz Dolny');
INSERT INTO cities (city_name) VALUES ('Kazimierza Wielka');
INSERT INTO cities (city_name) VALUES ('Kąty Wrocławskie');
INSERT INTO cities (city_name) VALUES ('Kcynia');
INSERT INTO cities (city_name) VALUES ('Kędzierzyn-Koźle');
INSERT INTO cities (city_name) VALUES ('Kępice');
INSERT INTO cities (city_name) VALUES ('Kępno');
INSERT INTO cities (city_name) VALUES ('Kętrzyn');
INSERT INTO cities (city_name) VALUES ('Kęty');
INSERT INTO cities (city_name) VALUES ('Kielce');
INSERT INTO cities (city_name) VALUES ('Kietrz');
INSERT INTO cities (city_name) VALUES ('Kisielice');
INSERT INTO cities (city_name) VALUES ('Kleczew');
INSERT INTO cities (city_name) VALUES ('Kleszczele');
INSERT INTO cities (city_name) VALUES ('Kluczbork');
INSERT INTO cities (city_name) VALUES ('Kłecko');
INSERT INTO cities (city_name) VALUES ('Kłobuck');
INSERT INTO cities (city_name) VALUES ('Kłodawa');
INSERT INTO cities (city_name) VALUES ('Kłodzko');
INSERT INTO cities (city_name) VALUES ('Knurów');
INSERT INTO cities (city_name) VALUES ('Knyszyn');
INSERT INTO cities (city_name) VALUES ('Kobylin');
INSERT INTO cities (city_name) VALUES ('Kobyłka');
INSERT INTO cities (city_name) VALUES ('Kock');
INSERT INTO cities (city_name) VALUES ('Kolbuszowa');
INSERT INTO cities (city_name) VALUES ('Kolno');
INSERT INTO cities (city_name) VALUES ('Kolonowskie');
INSERT INTO cities (city_name) VALUES ('Koluszki');
INSERT INTO cities (city_name) VALUES ('Kołaczyce');
INSERT INTO cities (city_name) VALUES ('Koło');
INSERT INTO cities (city_name) VALUES ('Kołobrzeg');
INSERT INTO cities (city_name) VALUES ('Koniecpol');
INSERT INTO cities (city_name) VALUES ('Konin');
INSERT INTO cities (city_name) VALUES ('Konstancin-Jeziorna');
INSERT INTO cities (city_name) VALUES ('Konstantynów Łódzki');
INSERT INTO cities (city_name) VALUES ('Końskie');
INSERT INTO cities (city_name) VALUES ('Koprzywnica');
INSERT INTO cities (city_name) VALUES ('Korfantów');
INSERT INTO cities (city_name) VALUES ('Koronowo');
INSERT INTO cities (city_name) VALUES ('Korsze');
INSERT INTO cities (city_name) VALUES ('Kosów Lacki');
INSERT INTO cities (city_name) VALUES ('Kostrzyn');
INSERT INTO cities (city_name) VALUES ('Kostrzyn nad');
INSERT INTO cities (city_name) VALUES ('Odrą');
INSERT INTO cities (city_name) VALUES ('Koszalin');
INSERT INTO cities (city_name) VALUES ('Kościan');
INSERT INTO cities (city_name) VALUES ('Kościerzyna');
INSERT INTO cities (city_name) VALUES ('Kowal');
INSERT INTO cities (city_name) VALUES ('Kowalewo Pomorskie');
INSERT INTO cities (city_name) VALUES ('Kowary');
INSERT INTO cities (city_name) VALUES ('Koziegłowy');
INSERT INTO cities (city_name) VALUES ('Kozienice');
INSERT INTO cities (city_name) VALUES ('Koźmin Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Kożuchów');
INSERT INTO cities (city_name) VALUES ('Kórnik');
INSERT INTO cities (city_name) VALUES ('Krajenka');
INSERT INTO cities (city_name) VALUES ('Kraków');
INSERT INTO cities (city_name) VALUES ('Krapkowice');
INSERT INTO cities (city_name) VALUES ('Krasnobród');
INSERT INTO cities (city_name) VALUES ('Krasnystaw');
INSERT INTO cities (city_name) VALUES ('Kraśnik');
INSERT INTO cities (city_name) VALUES ('Krobia');
INSERT INTO cities (city_name) VALUES ('Krosno');
INSERT INTO cities (city_name) VALUES ('Krosno Odrzańskie');
INSERT INTO cities (city_name) VALUES ('Krośniewice');
INSERT INTO cities (city_name) VALUES ('Krotoszyn');
INSERT INTO cities (city_name) VALUES ('Kruszwica');
INSERT INTO cities (city_name) VALUES ('Krynica Morska');
INSERT INTO cities (city_name) VALUES ('Krynica-Zdrój');
INSERT INTO cities (city_name) VALUES ('Krynki');
INSERT INTO cities (city_name) VALUES ('Krzanowice');
INSERT INTO cities (city_name) VALUES ('Krzepice');
INSERT INTO cities (city_name) VALUES ('Krzeszowice');
INSERT INTO cities (city_name) VALUES ('Krzywiń');
INSERT INTO cities (city_name) VALUES ('Krzyż Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Książ Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Kudowa-Zdrój');
INSERT INTO cities (city_name) VALUES ('Kunów');
INSERT INTO cities (city_name) VALUES ('Kutno');
INSERT INTO cities (city_name) VALUES ('Kuźnia Raciborska');
INSERT INTO cities (city_name) VALUES ('Kwidzyn');
INSERT INTO cities (city_name) VALUES ('Lądek-Zdrój');
INSERT INTO cities (city_name) VALUES ('Legionowo');
INSERT INTO cities (city_name) VALUES ('Legnica');
INSERT INTO cities (city_name) VALUES ('Lesko');
INSERT INTO cities (city_name) VALUES ('Leszno');
INSERT INTO cities (city_name) VALUES ('Leśna');
INSERT INTO cities (city_name) VALUES ('Leśnica');
INSERT INTO cities (city_name) VALUES ('Lewin Brzeski');
INSERT INTO cities (city_name) VALUES ('Leżajsk');
INSERT INTO cities (city_name) VALUES ('Lębork');
INSERT INTO cities (city_name) VALUES ('Lędziny');
INSERT INTO cities (city_name) VALUES ('Libiąż');
INSERT INTO cities (city_name) VALUES ('Lidzbark');
INSERT INTO cities (city_name) VALUES ('Lidzbark Warmiński');
INSERT INTO cities (city_name) VALUES ('Limanowa');
INSERT INTO cities (city_name) VALUES ('Lipiany');
INSERT INTO cities (city_name) VALUES ('Lipno');
INSERT INTO cities (city_name) VALUES ('Lipsk');
INSERT INTO cities (city_name) VALUES ('Lipsko');
INSERT INTO cities (city_name) VALUES ('Lubaczów');
INSERT INTO cities (city_name) VALUES ('Lubań');
INSERT INTO cities (city_name) VALUES ('Lubartów');
INSERT INTO cities (city_name) VALUES ('Lubawa');
INSERT INTO cities (city_name) VALUES ('Lubawka');
INSERT INTO cities (city_name) VALUES ('Lubień Kujawski');
INSERT INTO cities (city_name) VALUES ('Lubin');
INSERT INTO cities (city_name) VALUES ('Lublin');
INSERT INTO cities (city_name) VALUES ('Lubliniec');
INSERT INTO cities (city_name) VALUES ('Lubniewice');
INSERT INTO cities (city_name) VALUES ('Lubomierz');
INSERT INTO cities (city_name) VALUES ('Luboń');
INSERT INTO cities (city_name) VALUES ('Lubraniec');
INSERT INTO cities (city_name) VALUES ('Lubsko');
INSERT INTO cities (city_name) VALUES ('Lubycza Królewska');
INSERT INTO cities (city_name) VALUES ('Lwówek');
INSERT INTO cities (city_name) VALUES ('Lwówek Śląski');
INSERT INTO cities (city_name) VALUES ('Łabiszyn');
INSERT INTO cities (city_name) VALUES ('Łańcut');
INSERT INTO cities (city_name) VALUES ('Łapy');
INSERT INTO cities (city_name) VALUES ('Łasin');
INSERT INTO cities (city_name) VALUES ('Łask');
INSERT INTO cities (city_name) VALUES ('Łaskarzew');
INSERT INTO cities (city_name) VALUES ('Łaszczów');
INSERT INTO cities (city_name) VALUES ('Łaziska Górne');
INSERT INTO cities (city_name) VALUES ('Łazy');
INSERT INTO cities (city_name) VALUES ('Łeba');
INSERT INTO cities (city_name) VALUES ('Łęczna');
INSERT INTO cities (city_name) VALUES ('Łęczyca');
INSERT INTO cities (city_name) VALUES ('Łęknica');
INSERT INTO cities (city_name) VALUES ('Łobez');
INSERT INTO cities (city_name) VALUES ('Łobżenica');
INSERT INTO cities (city_name) VALUES ('Łochów');
INSERT INTO cities (city_name) VALUES ('Łomianki');
INSERT INTO cities (city_name) VALUES ('Łomża');
INSERT INTO cities (city_name) VALUES ('Łosice');
INSERT INTO cities (city_name) VALUES ('Łowicz');
INSERT INTO cities (city_name) VALUES ('Łódź');
INSERT INTO cities (city_name) VALUES ('Łuków');
INSERT INTO cities (city_name) VALUES ('Maków Mazowiecki');
INSERT INTO cities (city_name) VALUES ('Maków Podhalański');
INSERT INTO cities (city_name) VALUES ('Malbork');
INSERT INTO cities (city_name) VALUES ('Małogoszcz');
INSERT INTO cities (city_name) VALUES ('Małomice');
INSERT INTO cities (city_name) VALUES ('Margonin');
INSERT INTO cities (city_name) VALUES ('Marki');
INSERT INTO cities (city_name) VALUES ('Maszewo');
INSERT INTO cities (city_name) VALUES ('Miasteczko Śląskie');
INSERT INTO cities (city_name) VALUES ('Miastko');
INSERT INTO cities (city_name) VALUES ('Michałowo');
INSERT INTO cities (city_name) VALUES ('Miechów');
INSERT INTO cities (city_name) VALUES ('Miejska Górka');
INSERT INTO cities (city_name) VALUES ('Mielec');
INSERT INTO cities (city_name) VALUES ('Mieroszów');
INSERT INTO cities (city_name) VALUES ('Mieszkowice');
INSERT INTO cities (city_name) VALUES ('Międzybórz');
INSERT INTO cities (city_name) VALUES ('Międzychód');
INSERT INTO cities (city_name) VALUES ('Międzylesie');
INSERT INTO cities (city_name) VALUES ('Międzyrzec Podlaski');
INSERT INTO cities (city_name) VALUES ('Międzyrzecz');
INSERT INTO cities (city_name) VALUES ('Międzyzdroje');
INSERT INTO cities (city_name) VALUES ('Mikołajki');
INSERT INTO cities (city_name) VALUES ('Mikołów');
INSERT INTO cities (city_name) VALUES ('Mikstat');
INSERT INTO cities (city_name) VALUES ('Milanówek');
INSERT INTO cities (city_name) VALUES ('Milicz');
INSERT INTO cities (city_name) VALUES ('Miłakowo');
INSERT INTO cities (city_name) VALUES ('Miłomłyn');
INSERT INTO cities (city_name) VALUES ('Miłosław');
INSERT INTO cities (city_name) VALUES ('Mińsk Mazowiecki');
INSERT INTO cities (city_name) VALUES ('Mirosławiec');
INSERT INTO cities (city_name) VALUES ('Mirsk');
INSERT INTO cities (city_name) VALUES ('Mława');
INSERT INTO cities (city_name) VALUES ('Młynary');
INSERT INTO cities (city_name) VALUES ('Modliborzyce');
INSERT INTO cities (city_name) VALUES ('Mogielnica');
INSERT INTO cities (city_name) VALUES ('Mogilno');
INSERT INTO cities (city_name) VALUES ('Mońki');
INSERT INTO cities (city_name) VALUES ('Morąg');
INSERT INTO cities (city_name) VALUES ('Mordy');
INSERT INTO cities (city_name) VALUES ('Moryń');
INSERT INTO cities (city_name) VALUES ('Mosina');
INSERT INTO cities (city_name) VALUES ('Mrągowo');
INSERT INTO cities (city_name) VALUES ('Mrocza');
INSERT INTO cities (city_name) VALUES ('Mrozy');
INSERT INTO cities (city_name) VALUES ('Mszana Dolna');
INSERT INTO cities (city_name) VALUES ('Mszczonów');
INSERT INTO cities (city_name) VALUES ('Murowana Goślina');
INSERT INTO cities (city_name) VALUES ('Muszyna');
INSERT INTO cities (city_name) VALUES ('Mysłowice');
INSERT INTO cities (city_name) VALUES ('Myszków');
INSERT INTO cities (city_name) VALUES ('Myszyniec');
INSERT INTO cities (city_name) VALUES ('Myślenice');
INSERT INTO cities (city_name) VALUES ('Myślibórz');
INSERT INTO cities (city_name) VALUES ('Nakło nad');
INSERT INTO cities (city_name) VALUES ('Notecią');
INSERT INTO cities (city_name) VALUES ('Nałęczów');
INSERT INTO cities (city_name) VALUES ('Namysłów');
INSERT INTO cities (city_name) VALUES ('Narol');
INSERT INTO cities (city_name) VALUES ('Nasielsk');
INSERT INTO cities (city_name) VALUES ('Nekla');
INSERT INTO cities (city_name) VALUES ('Nidzica');
INSERT INTO cities (city_name) VALUES ('Niemcza');
INSERT INTO cities (city_name) VALUES ('Niemodlin');
INSERT INTO cities (city_name) VALUES ('Niepołomice');
INSERT INTO cities (city_name) VALUES ('Nieszawa');
INSERT INTO cities (city_name) VALUES ('Nisko');
INSERT INTO cities (city_name) VALUES ('Nowa Dęba');
INSERT INTO cities (city_name) VALUES ('Nowa Ruda');
INSERT INTO cities (city_name) VALUES ('Nowa Sarzyna');
INSERT INTO cities (city_name) VALUES ('Nowa Sól');
INSERT INTO cities (city_name) VALUES ('Nowe');
INSERT INTO cities (city_name) VALUES ('Nowe Brzesko');
INSERT INTO cities (city_name) VALUES ('Nowe Miasteczko');
INSERT INTO cities (city_name) VALUES ('Nowe Miasto');
INSERT INTO cities (city_name) VALUES ('Lubawskie');
INSERT INTO cities (city_name) VALUES ('Nowe Miasto nad Pilicą');
INSERT INTO cities (city_name) VALUES ('Nowe Skalmierzyce');
INSERT INTO cities (city_name) VALUES ('Nowe Warpno');
INSERT INTO cities (city_name) VALUES ('Nowogard');
INSERT INTO cities (city_name) VALUES ('Nowogrodziec');
INSERT INTO cities (city_name) VALUES ('Nowogród');
INSERT INTO cities (city_name) VALUES ('Nowogród Bobrzański');
INSERT INTO cities (city_name) VALUES ('Nowy Dwór Gdański');
INSERT INTO cities (city_name) VALUES ('Nowy Dwór');
INSERT INTO cities (city_name) VALUES ('Mazowiecki');
INSERT INTO cities (city_name) VALUES ('Nowy Sącz');
INSERT INTO cities (city_name) VALUES ('Nowy Staw');
INSERT INTO cities (city_name) VALUES ('Nowy Targ');
INSERT INTO cities (city_name) VALUES ('Nowy Tomyśl');
INSERT INTO cities (city_name) VALUES ('Nowy Wiśnicz');
INSERT INTO cities (city_name) VALUES ('Nysa');
INSERT INTO cities (city_name) VALUES ('Oborniki');
INSERT INTO cities (city_name) VALUES ('Oborniki Śląskie');
INSERT INTO cities (city_name) VALUES ('Obrzycko');
INSERT INTO cities (city_name) VALUES ('Odolanów');
INSERT INTO cities (city_name) VALUES ('Ogrodzieniec');
INSERT INTO cities (city_name) VALUES ('Okonek');
INSERT INTO cities (city_name) VALUES ('Olecko');
INSERT INTO cities (city_name) VALUES ('Olesno');
INSERT INTO cities (city_name) VALUES ('Oleszyce');
INSERT INTO cities (city_name) VALUES ('Oleśnica');
INSERT INTO cities (city_name) VALUES ('Olkusz');
INSERT INTO cities (city_name) VALUES ('Olsztyn');
INSERT INTO cities (city_name) VALUES ('Olsztynek');
INSERT INTO cities (city_name) VALUES ('Olszyna');
INSERT INTO cities (city_name) VALUES ('Oława');
INSERT INTO cities (city_name) VALUES ('Opalenica');
INSERT INTO cities (city_name) VALUES ('Opatów');
INSERT INTO cities (city_name) VALUES ('Opoczno');
INSERT INTO cities (city_name) VALUES ('Opole');
INSERT INTO cities (city_name) VALUES ('Opole Lubelskie');
INSERT INTO cities (city_name) VALUES ('Orneta');
INSERT INTO cities (city_name) VALUES ('Orzesze');
INSERT INTO cities (city_name) VALUES ('Orzysz');
INSERT INTO cities (city_name) VALUES ('Osieczna');
INSERT INTO cities (city_name) VALUES ('Osiek');
INSERT INTO cities (city_name) VALUES ('Ostrołęka');
INSERT INTO cities (city_name) VALUES ('Ostroróg');
INSERT INTO cities (city_name) VALUES ('Ostrowiec Świętokrzyski');
INSERT INTO cities (city_name) VALUES ('Ostróda');
INSERT INTO cities (city_name) VALUES ('Ostrów Lubelski');
INSERT INTO cities (city_name) VALUES ('Ostrów Mazowiecka');
INSERT INTO cities (city_name) VALUES ('Ostrów Wielkopolski');
INSERT INTO cities (city_name) VALUES ('Ostrzeszów');
INSERT INTO cities (city_name) VALUES ('Ośno Lubuskie');
INSERT INTO cities (city_name) VALUES ('Oświęcim');
INSERT INTO cities (city_name) VALUES ('Otmuchów');
INSERT INTO cities (city_name) VALUES ('Otwock');
INSERT INTO cities (city_name) VALUES ('Ozimek');
INSERT INTO cities (city_name) VALUES ('Ozorków');
INSERT INTO cities (city_name) VALUES ('Ożarów');
INSERT INTO cities (city_name) VALUES ('Ożarów Mazowiecki');
INSERT INTO cities (city_name) VALUES ('Pabianice');
INSERT INTO cities (city_name) VALUES ('Paczków');
INSERT INTO cities (city_name) VALUES ('Pajęczno');
INSERT INTO cities (city_name) VALUES ('Pakość');
INSERT INTO cities (city_name) VALUES ('Parczew');
INSERT INTO cities (city_name) VALUES ('Pasłęk');
INSERT INTO cities (city_name) VALUES ('Pasym');
INSERT INTO cities (city_name) VALUES ('Pelplin');
INSERT INTO cities (city_name) VALUES ('Pełczyce');
INSERT INTO cities (city_name) VALUES ('Piaseczno');
INSERT INTO cities (city_name) VALUES ('Piaski');
INSERT INTO cities (city_name) VALUES ('Piastów');
INSERT INTO cities (city_name) VALUES ('Piechowice');
INSERT INTO cities (city_name) VALUES ('Piekary Śląskie');
INSERT INTO cities (city_name) VALUES ('Pieniężno');
INSERT INTO cities (city_name) VALUES ('Pieńsk');
INSERT INTO cities (city_name) VALUES ('Pieszyce');
INSERT INTO cities (city_name) VALUES ('Pilawa');
INSERT INTO cities (city_name) VALUES ('Pilica');
INSERT INTO cities (city_name) VALUES ('Pilzno');
INSERT INTO cities (city_name) VALUES ('Piła');
INSERT INTO cities (city_name) VALUES ('Piława Górna');
INSERT INTO cities (city_name) VALUES ('Pińczów');
INSERT INTO cities (city_name) VALUES ('Pionki');
INSERT INTO cities (city_name) VALUES ('Piotrków Kujawski');
INSERT INTO cities (city_name) VALUES ('Piotrków Trybunalski');
INSERT INTO cities (city_name) VALUES ('Pisz');
INSERT INTO cities (city_name) VALUES ('Piwniczna-Zdrój');
INSERT INTO cities (city_name) VALUES ('Pleszew');
INSERT INTO cities (city_name) VALUES ('Płock');
INSERT INTO cities (city_name) VALUES ('Płońsk');
INSERT INTO cities (city_name) VALUES ('Płoty');
INSERT INTO cities (city_name) VALUES ('Pniewy');
INSERT INTO cities (city_name) VALUES ('Pobiedziska');
INSERT INTO cities (city_name) VALUES ('Poddębice');
INSERT INTO cities (city_name) VALUES ('Podkowa Leśna');
INSERT INTO cities (city_name) VALUES ('Pogorzela');
INSERT INTO cities (city_name) VALUES ('Polanica-Zdrój');
INSERT INTO cities (city_name) VALUES ('Polanów');
INSERT INTO cities (city_name) VALUES ('Police');
INSERT INTO cities (city_name) VALUES ('Polkowice');
INSERT INTO cities (city_name) VALUES ('Połaniec');
INSERT INTO cities (city_name) VALUES ('Połczyn-Zdrój');
INSERT INTO cities (city_name) VALUES ('Poniatowa');
INSERT INTO cities (city_name) VALUES ('Poniec');
INSERT INTO cities (city_name) VALUES ('Poręba');
INSERT INTO cities (city_name) VALUES ('Poznań');
INSERT INTO cities (city_name) VALUES ('Prabuty');
INSERT INTO cities (city_name) VALUES ('Praszka');
INSERT INTO cities (city_name) VALUES ('Prochowice');
INSERT INTO cities (city_name) VALUES ('Proszowice');
INSERT INTO cities (city_name) VALUES ('Prószków');
INSERT INTO cities (city_name) VALUES ('Pruchnik');
INSERT INTO cities (city_name) VALUES ('Prudnik');
INSERT INTO cities (city_name) VALUES ('Prusice');
INSERT INTO cities (city_name) VALUES ('Pruszcz Gdański');
INSERT INTO cities (city_name) VALUES ('Pruszków');
INSERT INTO cities (city_name) VALUES ('Przasnysz');
INSERT INTO cities (city_name) VALUES ('Przecław');
INSERT INTO cities (city_name) VALUES ('Przedbórz');
INSERT INTO cities (city_name) VALUES ('Przedecz');
INSERT INTO cities (city_name) VALUES ('Przemków');
INSERT INTO cities (city_name) VALUES ('Przemyśl');
INSERT INTO cities (city_name) VALUES ('Przeworsk');
INSERT INTO cities (city_name) VALUES ('Przysucha');
INSERT INTO cities (city_name) VALUES ('Pszczyna');
INSERT INTO cities (city_name) VALUES ('Pszów');
INSERT INTO cities (city_name) VALUES ('Puck');
INSERT INTO cities (city_name) VALUES ('Puławy');
INSERT INTO cities (city_name) VALUES ('Pułtusk');
INSERT INTO cities (city_name) VALUES ('Puszczykowo');
INSERT INTO cities (city_name) VALUES ('Pyrzyce');
INSERT INTO cities (city_name) VALUES ('Pyskowice');
INSERT INTO cities (city_name) VALUES ('Pyzdry');
INSERT INTO cities (city_name) VALUES ('Rabka-Zdrój');
INSERT INTO cities (city_name) VALUES ('Raciąż');
INSERT INTO cities (city_name) VALUES ('Racibórz');
INSERT INTO cities (city_name) VALUES ('Radków');
INSERT INTO cities (city_name) VALUES ('Radlin');
INSERT INTO cities (city_name) VALUES ('Radłów');
INSERT INTO cities (city_name) VALUES ('Radom');
INSERT INTO cities (city_name) VALUES ('Radomsko');
INSERT INTO cities (city_name) VALUES ('Radomyśl Wielki');
INSERT INTO cities (city_name) VALUES ('Radymno');
INSERT INTO cities (city_name) VALUES ('Radziejów');
INSERT INTO cities (city_name) VALUES ('Radzionków');
INSERT INTO cities (city_name) VALUES ('Radzymin');
INSERT INTO cities (city_name) VALUES ('Radzyń Chełmiński');
INSERT INTO cities (city_name) VALUES ('Radzyń Podlaski');
INSERT INTO cities (city_name) VALUES ('Rajgród');
INSERT INTO cities (city_name) VALUES ('Rakoniewice');
INSERT INTO cities (city_name) VALUES ('Raszków');
INSERT INTO cities (city_name) VALUES ('Rawa Mazowiecka');
INSERT INTO cities (city_name) VALUES ('Rawicz');
INSERT INTO cities (city_name) VALUES ('Recz');
INSERT INTO cities (city_name) VALUES ('Reda');
INSERT INTO cities (city_name) VALUES ('Rejowiec Fabryczny');
INSERT INTO cities (city_name) VALUES ('Resko');
INSERT INTO cities (city_name) VALUES ('Reszel');
INSERT INTO cities (city_name) VALUES ('Rogoźno');
INSERT INTO cities (city_name) VALUES ('Ropczyce');
INSERT INTO cities (city_name) VALUES ('Różan');
INSERT INTO cities (city_name) VALUES ('Ruciane-Nida');
INSERT INTO cities (city_name) VALUES ('Ruda Śląska');
INSERT INTO cities (city_name) VALUES ('Rudnik nad');
INSERT INTO cities (city_name) VALUES ('Sanem');
INSERT INTO cities (city_name) VALUES ('Rumia');
INSERT INTO cities (city_name) VALUES ('Rybnik');
INSERT INTO cities (city_name) VALUES ('Rychwał');
INSERT INTO cities (city_name) VALUES ('Rydułtowy');
INSERT INTO cities (city_name) VALUES ('Rydzyna');
INSERT INTO cities (city_name) VALUES ('Ryglice');
INSERT INTO cities (city_name) VALUES ('Ryki');
INSERT INTO cities (city_name) VALUES ('Rymanów');
INSERT INTO cities (city_name) VALUES ('Ryn');
INSERT INTO cities (city_name) VALUES ('Rypin');
INSERT INTO cities (city_name) VALUES ('Rzepin');
INSERT INTO cities (city_name) VALUES ('Rzeszów');
INSERT INTO cities (city_name) VALUES ('Rzgów');
INSERT INTO cities (city_name) VALUES ('Sandomierz');
INSERT INTO cities (city_name) VALUES ('Sanok');
INSERT INTO cities (city_name) VALUES ('Sejny');
INSERT INTO cities (city_name) VALUES ('Serock');
INSERT INTO cities (city_name) VALUES ('Sędziszów');
INSERT INTO cities (city_name) VALUES ('Sędziszów Małopolski');
INSERT INTO cities (city_name) VALUES ('Sępopol');
INSERT INTO cities (city_name) VALUES ('Sępólno Krajeńskie');
INSERT INTO cities (city_name) VALUES ('Sianów');
INSERT INTO cities (city_name) VALUES ('Siechnice');
INSERT INTO cities (city_name) VALUES ('Siedlce');
INSERT INTO cities (city_name) VALUES ('Siedliszcze');
INSERT INTO cities (city_name) VALUES ('Siemianowice Śląskie');
INSERT INTO cities (city_name) VALUES ('Siemiatycze');
INSERT INTO cities (city_name) VALUES ('Sieniawa');
INSERT INTO cities (city_name) VALUES ('Sieradz');
INSERT INTO cities (city_name) VALUES ('Sieraków');
INSERT INTO cities (city_name) VALUES ('Sierpc');
INSERT INTO cities (city_name) VALUES ('Siewierz');
INSERT INTO cities (city_name) VALUES ('Skalbmierz');
INSERT INTO cities (city_name) VALUES ('Skała');
INSERT INTO cities (city_name) VALUES ('Skarszewy');
INSERT INTO cities (city_name) VALUES ('Skaryszew');
INSERT INTO cities (city_name) VALUES ('Skarżysko-Kamienna');
INSERT INTO cities (city_name) VALUES ('Skawina');
INSERT INTO cities (city_name) VALUES ('Skępe');
INSERT INTO cities (city_name) VALUES ('Skierniewice');
INSERT INTO cities (city_name) VALUES ('Skoczów');
INSERT INTO cities (city_name) VALUES ('Skoki');
INSERT INTO cities (city_name) VALUES ('Skórcz');
INSERT INTO cities (city_name) VALUES ('Skwierzyna');
INSERT INTO cities (city_name) VALUES ('Sława');
INSERT INTO cities (city_name) VALUES ('Sławków');
INSERT INTO cities (city_name) VALUES ('Sławno');
INSERT INTO cities (city_name) VALUES ('Słomniki');
INSERT INTO cities (city_name) VALUES ('Słubice');
INSERT INTO cities (city_name) VALUES ('Słupca');
INSERT INTO cities (city_name) VALUES ('Słupsk');
INSERT INTO cities (city_name) VALUES ('Sobótka');
INSERT INTO cities (city_name) VALUES ('Sochaczew');
INSERT INTO cities (city_name) VALUES ('Sokołów Małopolski');
INSERT INTO cities (city_name) VALUES ('Sokołów Podlaski');
INSERT INTO cities (city_name) VALUES ('Sokółka');
INSERT INTO cities (city_name) VALUES ('Solec Kujawski');
INSERT INTO cities (city_name) VALUES ('Sompolno');
INSERT INTO cities (city_name) VALUES ('Sopot');
INSERT INTO cities (city_name) VALUES ('Sosnowiec');
INSERT INTO cities (city_name) VALUES ('Sośnicowice');
INSERT INTO cities (city_name) VALUES ('Stalowa Wola');
INSERT INTO cities (city_name) VALUES ('Starachowice');
INSERT INTO cities (city_name) VALUES ('Stargard');
INSERT INTO cities (city_name) VALUES ('Starogard Gdański');
INSERT INTO cities (city_name) VALUES ('Stary Sącz');
INSERT INTO cities (city_name) VALUES ('Staszów');
INSERT INTO cities (city_name) VALUES ('Stawiski');
INSERT INTO cities (city_name) VALUES ('Stawiszyn');
INSERT INTO cities (city_name) VALUES ('Stąporków');
INSERT INTO cities (city_name) VALUES ('Stepnica');
INSERT INTO cities (city_name) VALUES ('Stęszew');
INSERT INTO cities (city_name) VALUES ('Stoczek Łukowski');
INSERT INTO cities (city_name) VALUES ('Stopnica');
INSERT INTO cities (city_name) VALUES ('Stronie Śląskie');
INSERT INTO cities (city_name) VALUES ('Strumień');
INSERT INTO cities (city_name) VALUES ('Stryków');
INSERT INTO cities (city_name) VALUES ('Strzegom');
INSERT INTO cities (city_name) VALUES ('Strzelce Krajeńskie');
INSERT INTO cities (city_name) VALUES ('Strzelce Opolskie');
INSERT INTO cities (city_name) VALUES ('Strzelin');
INSERT INTO cities (city_name) VALUES ('Strzelno');
INSERT INTO cities (city_name) VALUES ('Strzyżów');
INSERT INTO cities (city_name) VALUES ('Sucha Beskidzka');
INSERT INTO cities (city_name) VALUES ('Suchań');
INSERT INTO cities (city_name) VALUES ('Suchedniów');
INSERT INTO cities (city_name) VALUES ('Suchowola');
INSERT INTO cities (city_name) VALUES ('Sulechów');
INSERT INTO cities (city_name) VALUES ('Sulejów');
INSERT INTO cities (city_name) VALUES ('Sulejówek');
INSERT INTO cities (city_name) VALUES ('Sulęcin');
INSERT INTO cities (city_name) VALUES ('Sulmierzyce');
INSERT INTO cities (city_name) VALUES ('Sułkowice');
INSERT INTO cities (city_name) VALUES ('Supraśl');
INSERT INTO cities (city_name) VALUES ('Suraż');
INSERT INTO cities (city_name) VALUES ('Susz');
INSERT INTO cities (city_name) VALUES ('Suwałki');
INSERT INTO cities (city_name) VALUES ('Swarzędz');
INSERT INTO cities (city_name) VALUES ('Syców');
INSERT INTO cities (city_name) VALUES ('Szadek');
INSERT INTO cities (city_name) VALUES ('Szamocin');
INSERT INTO cities (city_name) VALUES ('Szamotuły');
INSERT INTO cities (city_name) VALUES ('Szczawnica');
INSERT INTO cities (city_name) VALUES ('Szczawno-Zdrój');
INSERT INTO cities (city_name) VALUES ('Szczebrzeszyn');
INSERT INTO cities (city_name) VALUES ('Szczecin');
INSERT INTO cities (city_name) VALUES ('Szczecinek');
INSERT INTO cities (city_name) VALUES ('Szczekociny');
INSERT INTO cities (city_name) VALUES ('Szczucin');
INSERT INTO cities (city_name) VALUES ('Szczuczyn');
INSERT INTO cities (city_name) VALUES ('Szczyrk');
INSERT INTO cities (city_name) VALUES ('Szczytna');
INSERT INTO cities (city_name) VALUES ('Szczytno');
INSERT INTO cities (city_name) VALUES ('Szepietowo');
INSERT INTO cities (city_name) VALUES ('Szklarska Poręba');
INSERT INTO cities (city_name) VALUES ('Szlichtyngowa');
INSERT INTO cities (city_name) VALUES ('Szprotawa');
INSERT INTO cities (city_name) VALUES ('Sztum');
INSERT INTO cities (city_name) VALUES ('Szubin');
INSERT INTO cities (city_name) VALUES ('Szydłowiec');
INSERT INTO cities (city_name) VALUES ('Ścinawa');
INSERT INTO cities (city_name) VALUES ('Ślesin');
INSERT INTO cities (city_name) VALUES ('Śmigiel');
INSERT INTO cities (city_name) VALUES ('Śrem');
INSERT INTO cities (city_name) VALUES ('Środa Śląska');
INSERT INTO cities (city_name) VALUES ('Środa Wielkopolska');
INSERT INTO cities (city_name) VALUES ('Świątniki Górne');
INSERT INTO cities (city_name) VALUES ('Świdnica');
INSERT INTO cities (city_name) VALUES ('Świdnik');
INSERT INTO cities (city_name) VALUES ('Świdwin');
INSERT INTO cities (city_name) VALUES ('Świebodzice');
INSERT INTO cities (city_name) VALUES ('Świebodzin');
INSERT INTO cities (city_name) VALUES ('Świecie');
INSERT INTO cities (city_name) VALUES ('Świeradów-Zdrój');
INSERT INTO cities (city_name) VALUES ('Świerzawa');
INSERT INTO cities (city_name) VALUES ('Świętochłowice');
INSERT INTO cities (city_name) VALUES ('Świnoujście');
INSERT INTO cities (city_name) VALUES ('Tarczyn');
INSERT INTO cities (city_name) VALUES ('Tarnobrzeg');
INSERT INTO cities (city_name) VALUES ('Tarnogród');
INSERT INTO cities (city_name) VALUES ('Tarnowskie Góry');
INSERT INTO cities (city_name) VALUES ('Tarnów');
INSERT INTO cities (city_name) VALUES ('Tczew');
INSERT INTO cities (city_name) VALUES ('Terespol');
INSERT INTO cities (city_name) VALUES ('Tłuszcz');
INSERT INTO cities (city_name) VALUES ('Tolkmicko');
INSERT INTO cities (city_name) VALUES ('Tomaszów Lubelski');
INSERT INTO cities (city_name) VALUES ('Tomaszów Mazowiecki');
INSERT INTO cities (city_name) VALUES ('Toruń');
INSERT INTO cities (city_name) VALUES ('Torzym');
INSERT INTO cities (city_name) VALUES ('Toszek');
INSERT INTO cities (city_name) VALUES ('Trzcianka');
INSERT INTO cities (city_name) VALUES ('Trzciel');
INSERT INTO cities (city_name) VALUES ('Trzcińsko-Zdrój');
INSERT INTO cities (city_name) VALUES ('Trzebiatów');
INSERT INTO cities (city_name) VALUES ('Trzebinia');
INSERT INTO cities (city_name) VALUES ('Trzebnica');
INSERT INTO cities (city_name) VALUES ('Trzemeszno');
INSERT INTO cities (city_name) VALUES ('Tuchola');
INSERT INTO cities (city_name) VALUES ('Tuchów');
INSERT INTO cities (city_name) VALUES ('Tuczno');
INSERT INTO cities (city_name) VALUES ('Tuliszków');
INSERT INTO cities (city_name) VALUES ('Turek');
INSERT INTO cities (city_name) VALUES ('Tuszyn');
INSERT INTO cities (city_name) VALUES ('Twardogóra');
INSERT INTO cities (city_name) VALUES ('Tychowo');
INSERT INTO cities (city_name) VALUES ('Tychy');
INSERT INTO cities (city_name) VALUES ('Tyczyn');
INSERT INTO cities (city_name) VALUES ('Tykocin');
INSERT INTO cities (city_name) VALUES ('Tyszowce');
INSERT INTO cities (city_name) VALUES ('Ujazd');
INSERT INTO cities (city_name) VALUES ('Ujście');
INSERT INTO cities (city_name) VALUES ('Ulanów');
INSERT INTO cities (city_name) VALUES ('Uniejów');
INSERT INTO cities (city_name) VALUES ('Urzędów');
INSERT INTO cities (city_name) VALUES ('Ustka');
INSERT INTO cities (city_name) VALUES ('Ustroń');
INSERT INTO cities (city_name) VALUES ('Ustrzyki Dolne');
INSERT INTO cities (city_name) VALUES ('Wadowice');
INSERT INTO cities (city_name) VALUES ('Wałbrzych');
INSERT INTO cities (city_name) VALUES ('Wałcz');
INSERT INTO cities (city_name) VALUES ('Warka');
INSERT INTO cities (city_name) VALUES ('Warta');
INSERT INTO cities (city_name) VALUES ('Wasilków');
INSERT INTO cities (city_name) VALUES ('Wąbrzeźno');
INSERT INTO cities (city_name) VALUES ('Wąchock');
INSERT INTO cities (city_name) VALUES ('Wągrowiec');
INSERT INTO cities (city_name) VALUES ('Wąsosz');
INSERT INTO cities (city_name) VALUES ('Wejherowo');
INSERT INTO cities (city_name) VALUES ('Węgliniec');
INSERT INTO cities (city_name) VALUES ('Węgorzewo');
INSERT INTO cities (city_name) VALUES ('Węgorzyno');
INSERT INTO cities (city_name) VALUES ('Węgrów');
INSERT INTO cities (city_name) VALUES ('Wiązów');
INSERT INTO cities (city_name) VALUES ('Wieleń');
INSERT INTO cities (city_name) VALUES ('Wielichowo');
INSERT INTO cities (city_name) VALUES ('Wieliczka');
INSERT INTO cities (city_name) VALUES ('Wieluń');
INSERT INTO cities (city_name) VALUES ('Wieruszów');
INSERT INTO cities (city_name) VALUES ('Więcbork');
INSERT INTO cities (city_name) VALUES ('Wilamowice');
INSERT INTO cities (city_name) VALUES ('Witkowo');
INSERT INTO cities (city_name) VALUES ('Witnica');
INSERT INTO cities (city_name) VALUES ('Wleń');
INSERT INTO cities (city_name) VALUES ('Władysławowo');
INSERT INTO cities (city_name) VALUES ('Włocławek');
INSERT INTO cities (city_name) VALUES ('Włodawa');
INSERT INTO cities (city_name) VALUES ('Włoszczowa');
INSERT INTO cities (city_name) VALUES ('Wodzisław Śląski');
INSERT INTO cities (city_name) VALUES ('Wojcieszów');
INSERT INTO cities (city_name) VALUES ('Wojkowice');
INSERT INTO cities (city_name) VALUES ('Wojnicz');
INSERT INTO cities (city_name) VALUES ('Wolbórz');
INSERT INTO cities (city_name) VALUES ('Wolbrom');
INSERT INTO cities (city_name) VALUES ('Wolin');
INSERT INTO cities (city_name) VALUES ('Wolsztyn');
INSERT INTO cities (city_name) VALUES ('Wołczyn');
INSERT INTO cities (city_name) VALUES ('Wołomin');
INSERT INTO cities (city_name) VALUES ('Wołów');
INSERT INTO cities (city_name) VALUES ('Woźniki');
INSERT INTO cities (city_name) VALUES ('Wrocław');
INSERT INTO cities (city_name) VALUES ('Wronki');
INSERT INTO cities (city_name) VALUES ('Września');
INSERT INTO cities (city_name) VALUES ('Wschowa');
INSERT INTO cities (city_name) VALUES ('Wyrzysk');
INSERT INTO cities (city_name) VALUES ('Wysoka');
INSERT INTO cities (city_name) VALUES ('Wysokie Mazowieckie');
INSERT INTO cities (city_name) VALUES ('Wyszków');
INSERT INTO cities (city_name) VALUES ('Wyszogród');
INSERT INTO cities (city_name) VALUES ('Wyśmierzyce');
INSERT INTO cities (city_name) VALUES ('Zabłudów');
INSERT INTO cities (city_name) VALUES ('Zabrze');
INSERT INTO cities (city_name) VALUES ('Zagórów');
INSERT INTO cities (city_name) VALUES ('Zagórz');
INSERT INTO cities (city_name) VALUES ('Zakliczyn');
INSERT INTO cities (city_name) VALUES ('Zaklików');
INSERT INTO cities (city_name) VALUES ('Zakopane');
INSERT INTO cities (city_name) VALUES ('Zakroczym');
INSERT INTO cities (city_name) VALUES ('Zalewo');
INSERT INTO cities (city_name) VALUES ('Zambrów');
INSERT INTO cities (city_name) VALUES ('Zamość');
INSERT INTO cities (city_name) VALUES ('Zator');
INSERT INTO cities (city_name) VALUES ('Zawadzkie');
INSERT INTO cities (city_name) VALUES ('Zawichost');
INSERT INTO cities (city_name) VALUES ('Zawidów');
INSERT INTO cities (city_name) VALUES ('Zawiercie');
INSERT INTO cities (city_name) VALUES ('Ząbki');
INSERT INTO cities (city_name) VALUES ('Ząbkowice Śląskie');
INSERT INTO cities (city_name) VALUES ('Zbąszynek');
INSERT INTO cities (city_name) VALUES ('Zbąszyń');
INSERT INTO cities (city_name) VALUES ('Zduny');
INSERT INTO cities (city_name) VALUES ('Zduńska Wola');
INSERT INTO cities (city_name) VALUES ('Zdzieszowice');
INSERT INTO cities (city_name) VALUES ('Zelów');
INSERT INTO cities (city_name) VALUES ('Zgierz');
INSERT INTO cities (city_name) VALUES ('Zgorzelec');
INSERT INTO cities (city_name) VALUES ('Zielona Góra');
INSERT INTO cities (city_name) VALUES ('Zielonka');
INSERT INTO cities (city_name) VALUES ('Ziębice');
INSERT INTO cities (city_name) VALUES ('Złocieniec');
INSERT INTO cities (city_name) VALUES ('Złoczew');
INSERT INTO cities (city_name) VALUES ('Złotoryja');
INSERT INTO cities (city_name) VALUES ('Złotów');
INSERT INTO cities (city_name) VALUES ('Złoty Stok');
INSERT INTO cities (city_name) VALUES ('Zwierzyniec');
INSERT INTO cities (city_name) VALUES ('Zwoleń');
INSERT INTO cities (city_name) VALUES ('Żabno');
INSERT INTO cities (city_name) VALUES ('Żagań');
INSERT INTO cities (city_name) VALUES ('Żarki');
INSERT INTO cities (city_name) VALUES ('Żarów');
INSERT INTO cities (city_name) VALUES ('Żary');
INSERT INTO cities (city_name) VALUES ('Żelechów');
INSERT INTO cities (city_name) VALUES ('Żerków');
INSERT INTO cities (city_name) VALUES ('Żmigród');
INSERT INTO cities (city_name) VALUES ('Żnin');
INSERT INTO cities (city_name) VALUES ('Żory');
INSERT INTO cities (city_name) VALUES ('Żukowo');
INSERT INTO cities (city_name) VALUES ('Żuromin');
INSERT INTO cities (city_name) VALUES ('Żychlin');
INSERT INTO cities (city_name) VALUES ('Żyrardów');
INSERT INTO cities (city_name) VALUES ('Żywiec');

insert into rides values (1,2,4,"2019-11-01 10:00:00",120);
insert into rides_cities values (1,1,1,20,0,0);
insert into rides_cities values (2,1,3,10,60,0);
insert into rides_cities values (3,1,4,0,120,0);
insert into rides_users values (1,1,1,1,4);
